- .github/workflows/continuous-deployment.yml
- .github/workflows/continuous-integration.yml
> ci: use `node_modules` path instead of `~/.npm`

- package-lock.json
- package.json
We can just use `npx tailwind-config-viewer` instead of installing it
> chore: remove `tailwind-config-viewer`

- src/compositions/FormControl/FormControl.stories.tsx
- src/compositions/FormControl/FormControl.tsx
- src/elements/TextInput/TextInput.tsx
This PR removes the `HelperTextStyle` and adds a `FormControlStyle` which allows us to have the text input field and the helper text to be styled (for example when the input validation failed)
Here is an example with `FormControlStyle.Danger`:
> feat(Form Control): Add Form Control Styles

- src/components/ColorPicker/BrandColorPicker.tsx
- src/components/ColorPicker/CustomColorPicker.tsx
- src/components/Flyout/Flyout.spec.tsx
- src/elements/TextInput/TextInput.spec.tsx
- src/elements/TextInput/TextInput.stories.tsx
- src/elements/TextInput/TextInput.tsx
⚠️ **BREAKING CHANGES INCOMING** 
The `TextInput` was an uncontrolled component, which means that it handled the input value itself. This way we could only pass the `defaultValue`. When this one was updated, the changes weren't reflected in the input itself.
In our experience with React (and according to the docs) in most cases controlled form components are preferred over uncontrolled. Therefore this change does exactly this.
More info:
- Uncontrolled Components: https://reactjs.org/docs/uncontrolled-components.html
- Controlled Components: https://reactjs.org/docs/forms.html#controlled-components
> fix(Color Picker): Update Input Values When Changing Color With Drag and Drop

- src/elements/Checkbox/Checkbox.tsx
Currently the tooltip shows up with empty content for all checkboxes:
With this change we're only showing the tooltip if it's given:
> Fix: show checkbox tooltip only if it's given

- src/components/ColorPicker/BrandColorPicker.tsx
- src/components/ColorPicker/ColorPicker.spec.tsx
Concerns this ticket: https://app.clickup.com/t/nq8zf6
> fix: make grid default view for BrandColorPicker

- src/components/Checkbox/Checkbox.spec.tsx
- src/components/InputLabel/InputLabel.spec.tsx
- src/components/InputLabel/InputLabel.tsx
- src/components/TooltipIcon/TooltipIcon.spec.tsx
- src/components/TooltipIcon/TooltipIcon.stories.tsx
- src/components/TooltipIcon/TooltipIcon.tsx
- src/index.ts
**Changes:**
- Extracting the logic of tooltip and the icon that triggers it out of `InputLabel` and into a separate `TooltipIcon` component
- Using the newly created `TooltipIcon` component inside `InputLabel` in place of the previous code
- Allowing the new component to set the size of the icon
- Updating tests
Storybook: http://localhost:6006/?path=/story/components-tooltipicon--with-default-icon-size
> feat: Add TooltipIcon Component

- src/components/Dropdown/Dropdown.spec.tsx
- src/components/Dropdown/Dropdown.tsx
Allows the parent to pass the persistedIcon prop to the dropdown to display an icon at the beginning of the text input that doesn't get affected by the currently selected item.
> Feature - Add persisted icon to dropdown

- src/components/ColorInputFlyout/ColorPickerTrigger.tsx
- src/components/Dropdown/Dropdown.tsx
- src/components/MenuItem/MenuItemContent.tsx
- src/components/Trigger/Trigger.tsx
This fix eliminates gaps that don't handle click events around the dropdown text and the caret icon on the right-hand side.
> Fix unclickable areas inside dropdown

- src/components/TextInput/TextInput.tsx
Fixes an issue, where the TextInput wouldn't shrink down if placed in a relatively small parent e.g. inside the MultiInput
Relevant ticket: https://app.clickup.com/t/1vhxrbq
> fix: add width to TextInput

- src/components/ColorInputFlyout/ColorPickerTrigger.tsx
- src/components/Dropdown/Dropdown.tsx
Fixes the issue of having an absolutely positioned icon in the text input covering part of the text on smaller width sizes.
> Fix: Add padding to text input to prevent icon from covering it

- .gitignore
- src/components/Dropdown/Dropdown.tsx
Use `state.setSelectedKey()` when `activeItemId` prop is changed
from the outside.
You can reproduce the behavior in Storybook by changing the activeItemId prop.
> Update dropdown state by activeItemId prop

- src/components/ColorPicker/ColorPicker.tsx
- src/components/Flyout/Flyout.tsx
- Adds a new wrapper element around the color preview with sticky positioning and filled background color so that text scrolling behind is not visible if the alpha is not 1
- Label text is set to white if in dark mode and alpha is below 0.3
- Added overflow: auto to Flyout since default CSS behavior is overflow: visible
> fix(color-picker): sticky preview behaviour

- src/components/Slider/Slider.tsx
- src/foundation/Icon/Generated/index.ts
Issue: https://app.clickup.com/t/1u9qpk3
- Added layoutDependecy prop so that transition only occurs if the active item changes
> fix(slider): prevent transition on unrelated re-renders

- src/components/Slider/Slider.tsx
This fixes the issue that causes a "focus visible" ring to appear when the slider label is pressed for the second time inside an overlay.
Clickup link: https://app.clickup.com/t/1p0hg4a
> fix(slider): slider focus ring inside overlays

- src/components/ColorPicker/BrandColorPicker.tsx
- src/components/ColorPicker/ColorPicker.spec.tsx
- Empty color palettes are no longer displayed in the picker list
- Removed Titlecase on "Colors"
Clickup Ticket: https://app.clickup.com/t/1zngnky
> fix(color-picker): filter empty palettes

- src/components/FormControl/FormControl.tsx
Avoid double gap with `if label` to `if label?.children` and render children div only if `children` is set
> fix: avoid double gap

- package-lock.json
- package.json
- src/components/ColorInputFlyout/ColorInputTitle.tsx
- src/components/ColorInputFlyout/ColorPickerFlyout.spec.tsx
- src/components/ColorInputFlyout/ColorPickerFlyout.stories.tsx
- src/components/ColorInputFlyout/ColorPickerFlyout.tsx
- src/components/ColorInputFlyout/ColorPickerTrigger.tsx
- src/components/ColorPicker/BrandColorPicker.tsx
- src/components/ColorPicker/ColorPicker.spec.tsx
- src/components/ColorPicker/ColorPicker.stories.tsx
- src/components/ColorPicker/ColorPicker.tsx
- src/components/ColorPicker/CustomColorPicker.tsx
- src/components/ColorPicker/example-palettes.ts
- src/types/colors.ts
- src/utilities/colors.ts
This PR simplifies the color data structure as described in the following ticket, to avoid having colors in multiple color spaces (rgb, hex etc.): https://app.clickup.com/t/22b6p20
It also removes most of the utility methods in `src/utilities/colors.ts` and uses the `tinycolor2` library for color manipulation and conversion instead.
> refactor(color-picker)!: simplify color data structure

- package-lock.json
- package.json
Fixate arcade-tokens to 1.0.0-next.27, because the next release will be tailwind-3 compatible only.
> fix: Fixate arcade-tokens

- src/components/Flyout/Flyout.tsx
Recently encountered an issue while using the `Flyout` component where the content inside it wasn't nearly as wide as its default 400px min-width which ended up looking like this:
This PR fixes the issue by adding an optional prop to fit the `Flyout` component's width to the content inside it (setting min-width to 0).
End result:
> Feature: Support Flyout content width

- src/components/ColorInputFlyout/ColorPickerTrigger.tsx
- src/components/Dropdown/Dropdown.spec.tsx
- src/components/Dropdown/Dropdown.tsx
- src/components/MultiSelect/MultiSelect.tsx
- src/components/Tag/Tag.tsx
- src/components/Trigger/Trigger.tsx
This fix resolves issues related to the areas around the caret and clear icons not being clickable:
https://user-images.githubusercontent.com/26199969/151188319-471106d8-ff75-4f22-adf1-cd16cb393ecd.mov
Issues are resolved using `position: absolute` while adding enough padding for the input to not get covered by the icons.
End result:
https://user-images.githubusercontent.com/26199969/151188450-245c3d28-1575-4e4c-b23b-7afeabcbc89c.mov
A test is added to the test suite to prevent this from happening in the future.
Admittedly, the test could be improved (it takes the width of the element and subtracts some pixels from it to target the area where the bug occurs), but it works well on all screen widths I used to verify its correctness.
Another test could be added to test the area around the …
> Fix: Make areas around icons clickable

- src/components/Card/Card.stories.tsx
- src/components/Card/Card.tsx
Adds an optional `isHoverable` prop to the `Card` component to support the Brand Listening card design.
> feat: add hoverable state to card component

- src/components/LinkChooser/LinkChooser.spec.tsx
- src/components/LinkChooser/LinkChooser.stories.tsx
- src/components/LinkChooser/LinkChooser.tsx
- src/components/LinkChooser/NavigationMenu.tsx
- src/components/LinkChooser/SearchResultOption.tsx
- src/components/LinkChooser/SearchResultSection.tsx
- src/components/LinkChooser/SearchResultsList.tsx
- src/components/LinkChooser/mock/data.ts
- src/components/LinkChooser/mock/guidelines.ts
- src/components/LinkChooser/mock/templates.ts
- src/components/LinkChooser/sections.ts
- src/components/LinkChooser/state/actions.ts
- src/components/LinkChooser/state/machine.ts
- src/components/LinkChooser/types.ts
- src/components/LinkChooser/utils/helpers.ts
- src/components/RichTextEditor/RichTextEditor.tsx
Concerns this ticket: https://app.clickup.com/t/23yxnvc
This PR removes some of the Business Logic from the LinkChooser by replacing it with a more flexibel approach to add custom `extraSections`.
Keyboard navigation is only partly working and will be addressed in this follow-up ticket: https://app.clickup.com/t/24g28a0
> fix: decouple link chooser from clarify

- src/components/Flyout/Flyout.tsx
- src/components/Flyout/Overlay.tsx
This new logic is required to bridge the gap in logic between the Flyout component and the internals of react-aria useOverlay. React aria expects that the scrollRef is the outermost component of the overlay, and checks whether there is more pixels available in the preferred position than the scrollHeight of the scrollRef component and if not, it flips the position to the opposite side. 
Since the Flyout also must have the option to add a fixed header and a fixed footer, the size of these components must be added to the calculation that is done here https://github.com/adobe/react-spectrum/blob/7e8a7f69685139b3574453b424a5ad4c8fa4e808/packages/%40react-aria/overlays/src/calculatePosition.ts#L305, otherwise the function will not decide to flip the content because it thinks there is still …
> fix(Flyout): adjust Flyout positioning calculation

- src/components/Accordion/Accordion.stories.tsx
- src/components/Accordion/Accordion.tsx
This PR adds an option to have the content inside an accordion without left & right padding. This is need for the scroll-area in the targets selection.
> feat(Accordion): add padding option

- src/components/Dropdown/Dropdown.tsx
Fixes the text color of the selected item in the dropdown trigger.
Part of several sidebar fixes as described here: https://app.clickup.com/t/2326v0a
> fix: Dropdown active item color classes

- src/components/LinkChooser/LinkChooser.spec.tsx
- src/components/LinkChooser/NavigationMenu.tsx
- src/components/LinkChooser/SearchResultOption.tsx
Concerns this ticket: https://app.clickup.com/t/2329n7k
Adds a darker background color for hover and focus styles
> fix: change hover and focus color for search results in LinkChooser

- src/components/LinkChooser/LinkChooser.spec.tsx
- src/components/LinkChooser/LinkChooser.tsx
- src/components/LinkChooser/SearchResultOption.tsx
Fix for: https://app.clickup.com/t/24g28a0
- Menu navigation in extra sections is now possible
- Refactored search result option to avoid a visual glitch that would display ImageMenuItem components momentarily when closing the dropdown
> fix(link-chooser): keyboard navigation on extra panels

- src/components/Button/Button.spec.tsx
- src/components/Button/Button.stories.tsx
- src/components/Button/Button.tsx
This change introduces the property to render a button with a fully rounded radius. We need this to reflect the design of the legacy component `IconButton`, which was heavily used as a trigger for settings- and actions-menus, etc. Unless we have migrated all its occurrences to React, we can't easily switch to the new square design. As soon as we can switch to the new design, this property will be removed.
> feat: button rounded property

- src/typography/Heading/Heading.spec.tsx
- src/typography/Heading/Heading.stories.tsx
- src/typography/Heading/Heading.tsx
- src/typography/Text/Text.spec.tsx
- src/typography/Text/Text.stories.tsx
- src/typography/Text/Text.tsx
- src/typography/shared/Shared.stories.tsx
- src/typography/shared/records.ts
- src/typography/shared/types.ts
Add new controls that would be expected from a text component, including:
- overflow,
- whitespace,
- wordBreak,
- display,
- decoration
All classes correspond almost directly to tailwind classes, with the exception of some additional classes on the overflow control.
> feat(text/header): Add new typography props to text and header

- src/components/TextInput/TextInput.spec.tsx
- src/components/TextInput/TextInput.stories.tsx
- src/components/TextInput/TextInput.tsx
- src/hooks/useCopy.ts
Add a new property to the TextInput component to allow for copying the value of the input. 
Adds a new "useCopy" hook
> feat(TextInput): add copyable prop

- src/utilities/index.ts
This fixes build errors in clarify with the latest version of arcade due to Validation not being exported
> fix: export validation file

- src/components/Breadcrumbs/BreadcrumbItem.tsx
- src/components/Breadcrumbs/Breadcrumbs.spec.tsx
- src/components/Breadcrumbs/Breadcrumbs.tsx
- src/components/Breadcrumbs/CurrentBreadcrumbItem.tsx
> fix(Breadcrumbs): Move Hook Calls from Loops to Child Components

- src/components/Textarea/Textarea.spec.tsx
- src/components/Textarea/Textarea.stories.tsx
- src/components/Textarea/Textarea.tsx
Removing the `children` from the `<Textarea>` component and adding `value` prop instead, as discussed here: 
https://frontify.slack.com/archives/C02PSJTPA3D/p1646391887846429
> feat(Textarea)!: add value prop and remove children

- package-lock.json
- package.json
- src/components/ColorInputFlyout/ColorPickerTrigger.tsx
- src/components/ColorPicker/BrandColorPicker.tsx
- src/components/ColorPicker/ColorInput.tsx
- src/components/ColorPicker/ColorPicker.tsx
- src/components/ColorPicker/ColorPreview.tsx
- src/components/ColorPicker/CustomColorPicker.tsx
- src/components/ColorPicker/index.ts
- src/components/ColorPicker/styles.css
This PR changes the ColorPicker to use `react-colorful` library.
It also adds a border to the dropdown swatch, list swatches, and on the bottom edge of the color preview.
> feat(ColorPicker): refactor ColorPicker to use react-colorful

- src/components/RichTextEditor/RichTextEditor.tsx
- src/components/RichTextEditor/index.ts
- src/components/RichTextEditor/utils/parseRawValue.ts
Export the specified value of the empty rich text editor for use within clarify to implement the suggestion made here https://github.com/Frontify/clarify/pull/8165#discussion_r832395314
> fix(rte): export empty value

- src/components/Modal/Modal.tsx
This pr changes the modal max height to be dependent on the screen height, rather than what it was originally (fixed max height of 600px)
> fix(modal): remove fixed max height

- src/components/RichTextEditor/RichTextEditor.spec.tsx
This PR changes the test for multiple editors to render the editor directly with the different values, instead of typing into it. Previously the test failed randomly and no other solution could be found.
Ticket: https://app.clickup.com/t/29vhrb8
> fix(RichTextEditor): test for multiple editors

- src/components/Slider/Slider.tsx
Disables initial animation on Slider (when other value than the one on the far left is preselected).
> fix(Slider): disable initial animation

- renovate.json
Removes the `allNonMajor` as it is harder to fix the big PR, it was enabled to avoid spam in #arcade-notifications but now the Renovate will check once a week instead of everyday before
> chore: remove renovate update grouping

- src/components/ColorPicker/CustomColorPicker.tsx
- Allows the 'handles' to appear even if they are right at the edge or corner of the color picker
> fix(ColorPicker): remove overflow hidden from picker

- package-lock.json
- package.json
Issue is fixed: https://github.com/storybookjs/builder-vite/pull/346
Flyout in storybook should work as intended with this version of the package.
> chore: update storybook-builder-vite

- src/components/MultiSelect/MultiSelect.stories.tsx
- src/components/MultiSelect/MultiSelect.tsx
Add a non-transparent background to the multi-select dropdown menu. The easiest way to see the issue that this pr solves is to view the "MultiSelect With FormControl" storybook and remove the "tw-bg-base" class
> fix(MultiSelect): add non-transparent background

- src/components/Flyout/Flyout.stories.tsx
- src/components/Flyout/Flyout.tsx
- src/components/Flyout/Overlay.tsx
This adds a `minHeight` style prop for the Flyout content via a `contentMinHeight` component prop
[Loom demo](https://www.loom.com/share/df05651b51e9412fa2a846de835cbaeb)
> feat: Flyout min height

- src/components/AssetInput/SingleAsset/SelectedAsset.spec.tsx
- src/components/AssetInput/SingleAsset/SelectedAsset.tsx
On component mount the width is sometimes 0  when the parent container has `display:none` applied. (e.g. in Tabs, if the the parent tab container is not active).
Fix: applied a resize observer to keep the width calculation always up-to-date.
> fix(AssetInput): flyout width is calculated incorrectly

- src/components/RichTextEditor/RichTextEditor.spec.tsx
- src/components/RichTextEditor/RichTextEditor.stories.tsx
- src/components/RichTextEditor/RichTextEditor.tsx
- src/components/RichTextEditor/Toolbar.tsx
- src/components/RichTextEditor/utils/actions.ts
- src/components/RichTextEditor/utils/exampleValues.ts
This PR enables custom controls for the RTE by introducing a `action` prop. Subarray enable grouping of the controls.
Example:
`<RichTextEditor actions={[['link'],['italic','bold','underline'],['ordered-list','unordered-list']} />`
Result:
Ticket: https://app.clickup.com/t/2bmxh0x
> feat(RichTextEditor): enable controls customization

- src/components/FormControl/FormControl.spec.tsx
- src/components/FormControl/FormControl.tsx
Id's from child elements were being overwritten even if there was no label defined, meaning that random id's would take the place of defined id's on the child element
> fix(FormControl): fixed ids being stripped in form control

- src/components/Tabs/Tabs.tsx
Align with figma design https://www.figma.com/file/pevuvey1joCsopTRr9f4OE/Fondue-React-Components?node-id=14845%3A183245
The tab have actually padding-y of 16px
And the violet bar at the bottom is a bit too big
> style: add missing padding top to tabs

- scripts/templates/component.ts
I took the liberty of updating this as we decided not to use FC anymore. I think we should update the template when creating new components.
Some feedback about using PropsWithChildren in this template?
> fix: Fix create new component script template - remove FC

- src/components/Tooltip/Tooltip.tsx
The tooltip was not displayed when the trigger element was disabled. In case the trigger element is disabled it doesn't trigger any events, so the tooltip should be displayed when the mouse hovers over the trigger element container div.
> Fix tooltip display when trigger element is disabled.

- src/components/Tabs/Tabs.tsx
This pr fixes an issue where the layout animation occurs if the tab position is changes within the page.
To replicate:
In Arcade:
1. `npm link`
2. `npm run build`
In Clarify:
1. Make sure you have the MARKETPLACE dev flag enabled
2. `npm link @frontify/arcade`
3. `npm run dev`
4. visit [this url](https://dev.frontify.test/marketplace/type/integration/app/237f8362-ec03-4c86-86e3-314b4d0200b6?panel=overview)
5. Toggle between edit & view mode. There should be no animation or overflow bar when the position of the tab inside the page layout changes
> fix(Tabs): fix overflow scroll

- src/components/Tree/Node.tsx
- src/components/Tree/Tree.spec.tsx
- src/components/Tree/Tree.tsx
- src/components/Tree/utils/mocks.tsx
As discussed somewhat in the [Slack thread](https://frontify.slack.com/archives/C02PSJTPA3D/p1650372981299969).
I did the styling as it is in the [design for the Navigation Manager](https://www.figma.com/file/f37w3IPvu5wBpo0GakMNm0/Navigation?node-id=985%3A467784).
> feat(Tree): add badge icon to tree node item

- src/components/Modal/Modal.stories.tsx
- src/components/Modal/Modal.tsx
- src/components/Modal/ModalBody.tsx
- src/components/Modal/ModalFooter.tsx
- src/components/Modal/ModalHeader.tsx
- src/components/Modal/types.ts
- moves the `tw-p-14` padding class from the `<Modal>` and reproduces that padding with classes in the Modal Body, Header, and Footer.
- adds a `horizontalPadding` class to `Modal.Body` which defaults to `true`, to remove the horizontal padding class from the `Modal.Body` wrapper `div` when set to `false`
- adds a Story for demoing the new prop
> feat: add Modal.Body padding prop. move Modal padding into parts

- src/components/Button/Button.tsx
This adds an optional `formId` prop to `ButtonProps`, which is used in the `form` attribute on the `<Button>`. This associates the child `<button>` with a `<form id={formId} />` that it falls outside of, allowing a button to trigger `onSubmit` for a form even if it is outside the form in the DOM, such as when in a `<Flyout>` `fixedFooter`.
[via MDN:](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-form)
>form 
>The `<form>` element to associate the button with (its form owner). The value of this attribute must be the id of a `<form>` in the same document. (If this attribute is not set, the `<button>` is associated with its ancestor `<form>` element, if any.)
> 
> This attribute lets you associate `<button>` elements to `<form>`s anywhere in the document, not just …
> feat: Add formId prop and form attribute to Button

- src/components/Modal/Modal.stories.tsx
- src/components/Modal/Modal.tsx
- src/components/Modal/ModalBody.tsx
- src/components/Modal/ModalFooter.tsx
- src/components/Modal/ModalHeader.tsx
- src/components/Modal/context/ModalLayout.ts
- src/components/Modal/types.ts
- Adds a `padding` prop to the `<Modal>` to set either `Default` for `p-14` classes which result in 56px padding, or `Compact` for `p-6` classes which result in 24px padding. A `padding` object is distributed to Modal parts with a `layoutContext`
- Adds a storybook control for the `padding` prop and fixes the control for the `horizontalPadding` prop
> Feat: modal compact padding option

- src/components/Modal/Modal.tsx
- src/components/ScrollWrapper/ScrollWrapper.tsx
Prevents tooltip from automatically appearing when modal is opened, and also adds a tab-index to scrolling content so that it can be navigated via keyboard
> fix: prevent tooltip appearing in modal

- src/components/ActionMenu/ActionMenu/ActionMenu.tsx
- src/components/ActionMenu/Aria/AriaMenuItem.tsx
- src/components/AssetInput/SingleAsset/SelectedAsset.spec.tsx
- src/components/AssetInput/SingleAsset/SelectedAsset.tsx
Fixes the following Issue:
_Asset input stays open after clicking Replace with upload and doesn't close when a file is selected and processing When the file is processed the menu appears again (Firefox)_
Ticket:
https://app.clickup.com/t/2b5ep1f
> fix(AssetInput): Close Menu on Upload

- .git-blame-ignore-revs
- For PHPStorm a restart was needed to show the changes in annotations
- Possibly a [git config adjustment](https://michaelheap.com/git-ignore-rev/#:~:text=git%2Dblame%2Dignore%2Drevs,explain%20why%20it's%20being%20skipped.&text=Once%20the%20file%20exists%2C%20you,%2D%2Dignore%2Drevs%2Dfile%20.) is needed `git config --global blame.ignoreRevsFile .git-blame-ignore-revs`
> fix: Hide automatic formatter change from git blame: switching quotes

- src/components/Flyout/Flyout.tsx
- src/components/Flyout/hooks/useOverlayPositionWithBottomMargin.ts
Fixes issue with flyout recalculating flip on each render by instead setting inside of a useLayoutEffect. The Flyout will still listen to resize events on the window but it will not be buggy and change when the content changes.
An additional prop `updatePositionOnContentChange` has also been added to the Flyout to control a resizeObserver function that is called every time the height of the content changes (since this does not happen internally with react-aria). Setting this to true is useful when you have a Flyout that can contain variable content (ie. a Loading screen before a menu) and want the position to be calculated properly. The video attached contains an example of where this prop will come in useful. This prop is by default set to `false`, so components such as the …
> feat: add resize observer to Flyout

- src/components/ScrollWrapper/hooks/useScrollWrapper.ts
On retina screens the scrollTop sometimes returns half pixels, which can cause the gradient to not disappear because it detects there are still 0.5 pixels until the bottom of the scrollable content.
> fix(scrollWrapper): gradient does not disappear on retina screens

- src/components/Tree/Node.tsx
- src/components/Tree/Tree.spec.tsx
- src/components/Tree/components/EditableNodeItem.tsx
- src/components/Tree/utils/mocks.tsx
There was a use case that I missed when developing the badge and editable feature, they didn't work together.
This is basically just adding a prop to the `EditableNodeItem` component so it also includes the badge (or icon) if it exists.
> fix(Tree): Badge on editable tree node item

- .storybook/main.ts
Adds code splitting feature, dramatically improves build time of storybook, **but** individual stories still need time to load until they are available. -> https://storybook.js.org/blog/storybook-performance-from-webpack-to-vite/
> vite(storyStore): Build Stories on Demand, improve Storybook build time

- src/components/Modal/Modal.tsx
> style: remove overflow modal

- package-lock.json
- package.json
- src/components/Textarea/Textarea.spec.tsx
- src/components/Textarea/Textarea.stories.tsx
- src/components/Textarea/Textarea.tsx
Added a new feature to the Textarea component to be able to autosize when necessary. This component now has 3 new properties: autosize, minRows and maxRows. When setting the autosize to true (false by default) the textarea will automatically grow to max the size of the text until it hits the maxRow boundary. Since sizing is done computationally the resize handle for the textarea is removed for autosizing textareas.
> feat(Textarea): added autosize property

- src/components/Badge/Badge.spec.tsx
- src/components/Badge/Badge.stories.tsx
- src/components/Badge/Badge.tsx
Before:
Added ellipsis properties to text to prevent multi-line from forming when the badge shrinks
> feat(badge): added ellipsis to text

- src/components/RichTextEditor/RichTextEditor.spec.tsx
- src/components/RichTextEditor/utils/plaintext.ts
RTE returns value as string, so this PR extends the `toPlaintext` utility to parse it as JSON
> feat: parse JSON in RTE plaintext utility

- .github/workflows/continuous-deployment.yml
- .github/workflows/continuous-integration.yml
- .github/workflows/pull-request.yml
Component tests fail sometimes with missing npm dependencies when running them via GitHub Workflows
Add back the installation of dependencies, as we miss packages when the NPM cache does not provide them.
> fix(build): add back dependencies installation

- src/components/MultiSelect/MultiSelect.stories.tsx
- src/components/MultiSelect/MultiSelect.tsx
- src/components/MultiSelect/helpers.ts
- src/components/Tag/Tag.stories.tsx
- src/components/Tag/Tag.tsx
Add a smaller version to keep MultiSelect in line with other form components.
Before:
After:
> feat(MultiSelect): add smaller variant

- src/components/MultiSelect/MultiSelect.tsx
- src/components/MultiSelect/helpers.ts
This pr adds 8px of padding the right side of all multi select sizes due to the caret being to close to the badges inside the select, and also reduces left padding on the small multiselect from 20px to 12px.
> fix: reduce padding on x axis of small multiselect

- src/components/Tooltip/Tooltip.stories.tsx
- src/components/Tooltip/Tooltip.tsx
> fix(Tooltip): Fix styling for overflow texts.

- src/components/Badge/Badge.cy.tsx
- src/components/ColorInputFlyout/ColorInputTitle.tsx
- src/components/ColorInputFlyout/ColorPickerFlyout.cy.tsx
- src/components/ColorInputFlyout/ColorPickerFlyout.tsx
- src/components/ColorInputFlyout/ColorPickerTrigger.tsx
- src/components/ColorPicker/BrandColorPicker.tsx
- src/components/ColorPicker/ColorPicker.cy.tsx
- src/components/ColorPicker/ColorPicker.stories.tsx
- src/components/ColorPicker/ColorPreview.tsx
- src/components/ColorPicker/CustomColorPicker.tsx
- src/components/ColorPicker/example-palettes.ts
- src/types/colors.ts
- src/utilities/colors.ts
This PR changes the `ColorPicker` & `ColorInputFlyout` to work with the following color format to be consistent with the backend of Frontify.
```
{
"red":234,
"green":235,
"blue":235,
"alpha":1
}
```
Previously the short-notation rgb color format was used:
```
{
"r":234,
"g":235,
"b":235,
"a":1
}
```
> feat(ColorPicker)!: change color format

- .storybook/main.ts
In my opinion, storybook shouldn't throw in case of an eslint error, it's very disruptive to the dev flow.
> chore(eslint): Prevent runtime fail on eslint error

- src/components/Table/Table.tsx
- src/components/Table/TableCell.tsx
- src/components/Table/TableColumnHeader.tsx
- src/components/Table/TableHeaderRow.tsx
- src/components/Table/TableRow.tsx
- Remove react-aria from table components
- Improve keyboard navigation, both checkboxes and action buttons can now be navigated to and interacted with using tabs and space(validated with Jamie)
- Improve code by removing the child components dependency on the huge state object created in the <Table> component.
> chore(table): refactor components

- src/components/Table/Table.stories.tsx
- src/components/Table/Table.tsx
- src/components/Table/TableCell.tsx
- src/components/Table/TableColumnHeader.tsx
https://app.clickup.com/t/2t9epjp
- Fix selected border
- Fix hover on safari/firefox
- Fix a11y axe violations. Only one remaining which is unrelated to the table, but to the badge component. It should be fixed in a different PR with input from design, since it's a contrast issue
> fix(table): a11y violations and hover/selected style

- cypress.config.ts
Activate experimentalSingleTabRunMode to increase test performance
Component test time before: 12m 44s
Component test time in this PR: 6m 08s
--> -52% total running time!
Component tests should not fail
> chore(cypress): activate experimental single tab run mode

- src/components/Badge/Badge.tsx
The component should not define its own alignment. This PR removes self-alignment so it can be vertically centered with a flexbox wrapper or for example wrapped with the <Stack> component.
This change causes a break, as the environment was able to build on this problem.
> fix(badge)!: remove the self-alignment

- src/components/Modal/Modal.stories.tsx
The primary action button should be the furthest-right, to make our documentation clearer
Before:
After:
> fix(Modal): re-order buttons in documentation

- src/components/RichTextEditor/RichTextEditor.cy.tsx
- src/components/RichTextEditor/utils/parseRawValue.ts
When converting a textarea to a RTE as is a common case the saved value from the previous textarea which is plaintext will be added as the value of the RTE, causing the RTE to crash unexpectedly.
> feat(RichTextEditor): add plaintext support

- src/components/Tooltip/Tooltip.cy.tsx
- src/components/Tooltip/Tooltip.stories.tsx
- src/components/Tooltip/Tooltip.tsx
- Add the `open` boolean attribute to the Tooltip component. So it is possible to control the `isOpen` state from the outside like setting the tooltip box to be visible by default.
> The new attribute will not impact the normal behavior of the Tooltip component i.e. if it is open by default and the user interacts with the trigger element, the tooltip box will be visible when the mouse is over and hidden when the mouse is out.
> feat(Tooltip): add open boolean prop to the component

- src/components/Table/Table.cy.tsx
- src/components/Table/Table.stories.tsx
- src/components/Table/Table.tsx
- src/components/Table/TableColumnHeader.tsx
☝️ Now columns are optionally sortable with a prop and the sorting logic is exposed so that it can be customizable, which we need in analytics
> chore: move sorting logic from out of fondue and allow optional sorting columns

- src/components/TextInput/TextInput.tsx
Currently the text input does not have the same styling as the dropdown, color input and textarea because it does not have a border color change on hover
> fix(TextInput): add input hover border style

- src/components/Checkbox/Checkbox.tsx
- src/components/Checklist/Checklist.stories.tsx
- src/components/InputLabel/InputLabel.tsx
Since the children of this component were not flex children they were overflowing incorrectly, as below
> fix(Checklist): enforce correct vertical spacing

- src/components/Flyout/Flyout.stories.tsx
- src/components/TextInput/TextInput.tsx
This PR fixes the issue with the `TextInput` component `focusOnMount` prop on the first render when inside a `Flyout` component.
- If the page had scrolling, it would try to focus the element on the first DOM position it is placed, forcing the page to scroll down and the `Flyout` to close.
> The solution was to put the input field focus side-effect inside a `setTimeout(() => {}, 0);` so it could happen on the next event loop, making sure the `Flyout` and the `TextInput` are properly mounted and positioned, avoiding the scrolling and the `Flyout` to close.
> fix(TextInput): add zero timeout for focusing the text input after mounting

- src/components/Tooltip/Tooltip.cy.tsx
- src/components/Tooltip/Tooltip.stories.tsx
- src/components/Tooltip/Tooltip.tsx
This PR adds two new properties to the `Tooltip` component
- `disabled` -> disables tooltip functionality. The tooltip content will not be rendered at all;
- `hidden` -> hides the tooltip content. The content is rendered but hidden with a `display: none;` through Tailwind `tw-hidden` class
New stories and test cases were also added for the new properties.
> feat(Tooltip): add disabled and hidden props to component

- src/components/OrderableList/OrderableList.tsx
- There was a bug with the orderable list because the fragment around had no key associated with it.
> fix(OrderableList): add fragment with key 

- src/components/DatePicker/DatePicker.css
- src/components/DatePicker/DatePicker.stories.tsx
This PR changes the datepicker calendar `z-index`.
The problem: when using the `Datepicker` right before a `Slider`, the date picker was placed underneath the slider which has a `z-index: 10`.
The solution: Changed the `Datepicker.css` to override the class `.react-datepicker-popper` which was setting the `z-index: 1` to `z-index: 40`. This value is because the default `Modal` `z-index` value is 50, so we can assure a datepicker will not be placed above a modal, if for some reason the two of them are on the screen at the same time.
> fix(DatePicker): adjust datepicker popper class to have a higher z-index value

- src/components/TextInput/TextInput.tsx
Fixing my own issue introducing a hover style that should only be visible when the input is interactive 😅 
Before:
After:
> fix(TextInput): remove hover style on disabled input

- src/components/Button/Button.tsx
React-aria always trigger the focusring when clicking the button. Removing react-aria fixes this issue and does not harm any accessibility criterias.
> fix(Button): remove button react-aria

- src/components/EditableText/EditableText.stories.tsx
isOverflowing shouldn't be visible in Storybook as it is a property added only to fix the overflow in the Tree component.
> fix(EditableText): Hide isOverflowing control

- src/components/RichTextEditor/RichTextEditor.tsx
- src/components/RichTextEditor/utils/parseRawValue.ts
This PR provides the editor id to `createPlateEditor` inside `parseRawValue` to prevent an infinite loop when multiple editors are used on the same page in clarify.
Loom of the issue: https://www.loom.com/share/e3cbdc35a88140649107933ee9373d92
> fix(RichTextEditor): infinite loop inside parseRawValue

- src/components/RichTextEditor/RichTextEditor.cy.tsx
- src/components/RichTextEditor/RichTextEditor.tsx
- src/components/RichTextEditor/utils/parseRawValue.ts
It is breaking the Clarify test with infinite rendering.
The Fondue beta 10 is working normally the 11 is breaking.
> fix(Rich Text Editor): Removed editor id prop from parsing method

- src/components/RichTextEditor/RichTextEditor.tsx
- src/components/RichTextEditor/serializer/serializeToHtml.ts
- src/components/RichTextEditor/utils/parseRawValue.ts
Redo changes from https://github.com/Frontify/fondue/pull/1008, which were reverted in https://github.com/Frontify/fondue/pull/1010. This time it's an unique id for the `parseRawValue`-method and switched to an object for the parameters.
How to test this with clarify (as linking fondue to clarify is somehow not working currently):
- fondue: `npm run build`
- copy folder `dist` from **fondue** to **clarify/node_modules/@frontify/fondue**
- run tests
> fix: provide unique id to createPlateEditor

- src/components/RichTextEditor/RichTextEditor.cy.tsx
- src/components/RichTextEditor/RichTextEditor.tsx
- src/components/RichTextEditor/hooks/useEditorState.ts
Refactored useEditorState while usePlateEditorState should be called inside Plate editor.
Because we don't use the clear prop I removed it, to clear it is also possible to pass empty value.
Removed also corresponding tests
> fix(Rich Text Editor): hook not called inside plate editor

- src/components/Tooltip/Tooltip.cy.tsx
- src/components/Tooltip/Tooltip.stories.tsx
- src/components/Tooltip/Tooltip.tsx
The optional enterDelay prop defines the amount of time that should pass before the tooltip becomes visible. If not defined, the tooltip will render immediately.
https://app.clickup.com/t/32yf5y9
> feat(Tooltip): add enterDelay prop

- src/components/RichTextEditor/Plugins/LinkPlugin/LinkMarkupElement/LinkMarkupElementNode.tsx
- src/components/RichTextEditor/serializer/utils/serializeLeafToHtml.ts
- src/components/RichTextEditor/serializer/utils/serializeNodeToHtmlRecursive.ts
Fixing Type errors listed when running `npm run typecheck`
Because of the complexity and not being able to easily define a type and using `unknown` is not an option, type `any` will be used.
The decision being that is preferable to have a lint warning for `no-explicit-any` than a type error.
> refactor(Rich Text Editor): Fix type errors

- src/components/RichTextEditor/hooks/useEditorResize.ts
Prevents visual glitch that can be seen here for 10ms immediately after rendering, caused by debounce. https://fondue-components.frontify.com/?path=/story/components-rich-text-editor--with-toolbar-top-and-small-padding
> fix(rte): immediately set editor width when node is rendered

- src/components/Dropdown/Dropdown.tsx
- src/components/Dropdown/SelectMenu/SelectMenu.tsx
- src/components/Dropdown/SelectMenu/SelectMenuItem.tsx
- src/components/Dropdown/SelectMenu/SelectMenuSection.tsx
- src/components/MenuItem/MenuItem.tsx
- src/components/Trigger/Trigger.tsx
Hey,
I changed the dropdown component to now use only alias tokens. Hope everything looks like before but with other tokens.
- To test its best to add the tw-dark class to the body of the iframe in the storybook, because the portal moves the html end of the document and is not covered by a tw-dark.
> fix(dropdown): add alias tokens and remove brand tokens

- package-lock.json
- package.json
Updating dependencies in small parts to prepare the migration to React 18.
Using current version of Fondue in a react 18 app gives `./jsx-runtime.js is not exported from package (react-dnd)` error.
Fix: update react-dnd to version 16.0.1
To be tested without using `npm link`
> chore(deps): upgrade react-dnd

- src/components/RichTextEditor/types.ts
Property `hover` should be optional in `DesignTokens` type, see: [useGuidelineDesignTokens.ts#L73](https://github.com/Frontify/guideline-blocks/blob/main/packages/shared/src/hooks/useGuidelineDesignTokens.ts#L73)
> fix(RTE): make hover optional in DesignTokens type

- src/components/Modal/ModalFooter.tsx
- src/components/Modal/types.ts
Fixes issue introduced when upgrading react-aria as some types changed and `shouldCloseOnBlur` have moved to another type
> fix: use correct react aria typing

- src/components/RichTextEditor/RichTextEditor.tsx
- src/components/RichTextEditor/hooks/useEditorState.ts
- src/components/RichTextEditor/utils/parseRawValue.ts
To test:
Replace this story with the following 
```
export const SerializedToHTML: StoryFn<RichTextEditorProps> = ({ onTextChange }) => {
const serialized =
'<ul class="tw-list-disc tw-pl-[10px] tw-mb-[10px] tw-ml-[25px]"><li style="font-size: 14px; font-style: normal; font-weight: normal; line-height: 16px; text-decoration: none;"><span style>padding</span></li></ul><ol class="tw-pl-[10px] tw-mb-[10px] tw-ml-[25px] tw-list-[decimal]"><li style="font-size: 14px; font-style: normal; font-weight: normal; line-height: 16px; text-decoration: none;"><span style>test</span></li></ol><p style="font-size: 14px; font-style: normal; font-weight: normal; line-height: 16px;"></p><p style="font-size: 14px; font-style: normal; font-weight: normal; line-height: 16px;"><a href="/" style="font-size: 14px; …
```
> fix: normalize initial html value for rich text editor

- src/components/RichTextEditor/Plugins/BreakAfterPlugin/BreakAfterButton/BreakAfterToolbarButton.tsx
within `clarify` and `guideline-blocks` are the used tailwind classes not available. Now they are updated to the ones available. Can be tested within `text-block` by linking fondue to `guideline-block` and to `clarify`
> feat(RichTextEditor): fix tailwind classes within tooltip

- src/components/Tabs/TabItem.tsx
- src/components/Tabs/Tabs.cy.tsx
- src/utilities/elements.ts
Issue:
When tabbing, the tab content panel always focus.
Fix:
The focus should be on the whole panel when no interactive elements are present. Else, you should tab directly to whatever you can interact with inside of it.
> fix(Tabs): Tab and focus on tab panel only when no interactive content.

- src/components/MultiSelect/MultiSelect.tsx
The height wasn't matching the new design, here, should be 36px instead of 42px: https://www.figma.com/file/WfEbqZI0nnPWHN43MCtvnm/Fondue---Inputs?node-id=43%3A32279&t=1JXIVp1n0yuj7EAa-4
CC @SamCreasey
> fix(trigger): fix padding on small variant

- src/components/Tabs/Tabs.tsx
The id was being used in an alphabetized comparison, but if the id's of the tabs were not in order then it broke keyboard accessibility. Using the index ensures that custom tab id's can be used
> fix: allow custom ids on tab to be ordered

- src/components/MultiSelect/MultiSelect.tsx
So this fix includes two things:
- Displaying summarizedLabel regardless if there are selected items defined
- If summarized label is shown, remove clear button if no indeterminate keys are existing
> fix(MultiSelect): multi select summarized label

- src/components/RichTextEditor/Plugins/LinkPlugin/FloatingLink/CustomFloatingLink.tsx
Previously the LinkChooser could be opened even in `readonly` mode, see [loom](https://www.loom.com/share/50abc1c4b96541a3b5b0c0cd44977b12).
> fix(RTE): disable LinkChooser in readonly mode

- src/components/MultiSelect/MultiSelect.tsx
Flip is flaky on overlays with dynamic height calculation and use of popper.js for positioning.
Rule of Animation:
If the animation is causing more trouble than it delivers value, Don't animate.
> fix(MultiSelect): Disable animation to enable flip

- src/components/Slider/Slider.tsx
Tested on Chrome, Safari, Firefox and Edge
> fix(Slider): add a flex wrapper for buttons to have the full height

- src/components/ColorInputFlyout/ColorPickerFlyout.tsx
- src/components/ColorInputFlyout/ColorPickerTrigger.tsx
- src/components/Flyout/Flyout.tsx
- src/components/Flyout/FlyoutFooter.tsx
- src/components/Trigger/Trigger.tsx
The `Flyout` component is using the `buttonProps` returned by the `react-aria` `useButton` hook on a div. So even with the `Trigger` being disabled, that div on the `Flyout` was triggering the `toggle` function to open it.
A new optional prop `isTriggerDisabled` was added to the component and the `ColorPickerFlyout` `disabled` prop is being passed down to all the child components.
> fix(ColorPickerFlyout): flyout opening when disabled is true

- src/components/RichTextEditor/Plugins/CodePlugin/CodeMarkupElement.tsx
- src/components/RichTextEditor/__tests__/RichTextEditor.cy.tsx
- src/components/RichTextEditor/serializer/utils/serializeNodeToHtmlRecursive.ts
When rendering a text like 
```{
type: ELEMENT_PARAGRAPH,
children: [{ text: 'This text is a code', code: true }, { text: ' line' }, { text: '.', code: true }],
},
```
the serialized html was rendered on three lines instead of just one.
> fix(RichTextEditor): fix code markup element in html rendering

- src/components/RichTextEditor/helpers/exampleValues/exampleValues.ts
- src/components/RichTextEditor/serializer/nodes/checkItem.ts
- src/components/RichTextEditor/serializer/serializeToHtml.spec.ts
- src/components/RichTextEditor/serializer/serializeToHtml.ts
- src/components/RichTextEditor/serializer/utils/serializeLeafToHtml.spec.ts
- src/components/RichTextEditor/serializer/utils/serializeLeafToHtml.ts
[Ticket: checklist points](https://app.clickup.com/t/8677a1v57)
When saving a text to link it is saved as following:
```
{
type: ELEMENT_PARAGRAPH,
children: [
{ text: '' },
{
type: ELEMENT_LINK,
children: [{ text: 'This is a Link. Without any breaks before or after' }],
url: 'https://frontify.com',
},
{ text: '' },
],
},
```
this caused the element to have a line break before and after the link in view mode.
> fix(RichTextEditor): serialize checked checklist and link correct to html

- src/components/Tooltip/Tooltip.tsx
Fixes a missing tooltip race condition caused by the setTimeout being triggered  just before the tooltip was disabled, which sets the tooltip back to 'open' even if it is disabled
> fix: tooltip race condition

- src/components/RichTextEditor/Plugins/AlignPlugin/AlignCenterPlugin/AlignCenterButton.tsx
- src/components/RichTextEditor/Plugins/AlignPlugin/AlignJustifyPlugin/AlignJustifyButton.tsx
- src/components/RichTextEditor/Plugins/AlignPlugin/AlignLeftPlugin/AlignLeftButton.tsx
- src/components/RichTextEditor/Plugins/AlignPlugin/AlignRightPlugin/AlignRightButton.tsx
- src/components/RichTextEditor/Plugins/BoldPlugin/BoldButton.tsx
- src/components/RichTextEditor/Plugins/ButtonPlugin/components/ButtonButton.tsx
- src/components/RichTextEditor/Plugins/ButtonPlugin/components/ButtonToolbarButton.tsx
- src/components/RichTextEditor/Plugins/CheckboxListPlugin/CheckboxListButton/index.tsx
- src/components/RichTextEditor/Plugins/CodePlugin/CodeButton.tsx
- src/components/RichTextEditor/Plugins/ColumnBreakPlugin/ColumnBreakButton/ColumnBreakToolbarButton.tsx
- src/components/RichTextEditor/Plugins/ColumnBreakPlugin/ColumnBreakButton/index.tsx
- src/components/RichTextEditor/Plugins/EmojiPlugin/EmojiButton.tsx
- src/components/RichTextEditor/Plugins/ItalicPlugin/ItalicButton.tsx
- src/components/RichTextEditor/Plugins/LinkPlugin/LinkButton.tsx
- src/components/RichTextEditor/Plugins/ListPlugin/OrderedListPlugin/OrderedListButton.tsx
- src/components/RichTextEditor/Plugins/ListPlugin/UnorderedListPlugin/UnorderedListButton.tsx
- src/components/RichTextEditor/Plugins/ResetFormattingPlugin/ResetFormattingButton/index.tsx
- src/components/RichTextEditor/Plugins/StrikethroughPlugin/StrikethroughButton.tsx
- src/components/RichTextEditor/Plugins/UnderlinePlugin/UnderlineButton.tsx
- src/components/RichTextEditor/Plugins/helper.tsx
- src/components/RichTextEditor/__tests__/RichTextEditor.cy.tsx
- src/components/RichTextEditor/__tests__/fixtures/selectors.ts
Disables a link-button or button-button when multiple blocks are selected in the rich text editor, since it's not yet supported by the rich text editor plugin itself.
> feat(RichTextEditor): disable link- and button-button when multiple blocks are selected

- src/components/Tree/TreeItem.tsx
Temporary fix until the dnd-kit stuff is finalized. Basically, the Dropzone is positioned over the TreeItem so the hoverable area is clunky.
> feat(TreeItem): Content hover fix

- src/components/RichTextEditor/Plugins/ButtonPlugin/components/ButtonToolbarButton.tsx
- src/components/RichTextEditor/helpers/getTooltip.tsx
- Adjust tooltip of button to design
- Make first line of tooltip text bold
Design: https://www.figma.com/file/pevuvey1joCsopTRr9f4OE/Fondue---Components?t=ztBDUH5mf6Xip7lO-0
Ticket: https://app.clickup.com/t/8677hy3g9
> feat(RTE): make first line on tooltip bold

- src/components/RichTextEditor/serializer/nodes/link.ts
At transformation to HTML the link when clicked is set to not propagate.
If the link is inside container which is event action the link should not bubble events to the parent.
> fix: stop link to propagate

- pnpm-lock.yaml
- src/components/RichTextEditor/Plugins/ListPlugin/ListItemContentMarkupElement.tsx
- src/components/RichTextEditor/Plugins/ListPlugin/OrderedListPlugin/OrderedListMarkupElement.tsx
- src/components/RichTextEditor/Plugins/ListPlugin/UnorderedListPlugin/UnorderedListMarkupElement.tsx
- src/components/RichTextEditor/__tests__/RichTextEditor.cy.tsx
- src/components/RichTextEditor/serializer/utils/reactCssPropsToCss.spec.ts
- src/components/RichTextEditor/serializer/utils/reactCssPropsToCss.ts
- src/components/RichTextEditor/serializer/utils/serializeNodeToHtmlRecursive.spec.ts
- src/components/RichTextEditor/serializer/utils/serializeNodeToHtmlRecursive.ts
Replace all double quotes to single quotes in css values, because otherwise it causes issues:
Ticket: https://app.clickup.com/t/8677k32g3
> fix(RTE): quotes in serializer

- package.json
Preinstall script gets executed on target systems as well and takes around 10s to execute or even more. We get the same result by using engine definitions for PNPM and block NPM by defining a not available version.
- NPM should not be able to do the installation
- PNPM should install the project like before
> chore(setup): replace preinstall script with engine definition

- .github/workflows/continuous-deployment.yml
Removed superfluous step "Use pnpm", because it was there twice .
> chore(workflows): remove duplicated step

- src/components/RichTextEditor/context/index.ts
- src/components/RichTextEditor/index.ts
Export RTE context, so we can reuse it in `guideline-blocks`
> feat(RTE): export context

- .github/workflows/release-preview.yml
Saving the Release Notes to the step summary was failing due to invalid characters in the returned markdown.
Until we find a good solution for this issue, printing the release notes preview markdown to the console (default behaviour of `semantic-release --dry-run --no-ci`) is enough.
We can copy the markdown output and paste as the PR into `main` description and edit it there until we have the proper documentation for making the release.
> chore(release-skip): only print release notes preview to job console

- src/components/Tree/Tree.cy.tsx
- src/components/Tree/TreeItem/TreeItem.tsx
- src/components/Tree/utils/mocks.ts
Align non-draggable items on tree: cover page and all brands link.
Including a non-draggable item on storybook as well
Before:
After:
https://app.clickup.com/t/862jp8qqf
> fix: align not draggable items on tree

- src/components/Tree/TreeItem/TreeItem.tsx
Fixes issue about active item on nm is not visible when DnD item displace it:
Before:
After:
> fix: nm active element colors on dnd

- src/components/AssetInput/AssetInput.tsx
Unfortunately there isn't any option in cypress to check if the file dialog of the OS opened, so i couldn't add tests for the fix
> fix(assetInput): accessibility for the file upload field

- src/components/Tree/Tree.tsx
This PR fixes the issue present when an item gets deleted and stays dangling around in the tree because it stays registered but it doesn't actually belongs to any parent.
Adds a filter for the nodes array to remove those items not belonging anymore to its parent.
https://app.clickup.com/t/861mqzbb8
> fix: nm tree dangling deleted item

- src/components/Tree/TreeItem/TreeItem.tsx
- src/components/Tree/types.ts
Adds the possibility to get the `parentType` of the zone we drop in
> feat: add `parentType` in the drop callback

- src/components/Tree/Tree.tsx
- src/components/Tree/TreeItem/DragHandle.tsx
Fixes a couple of accessibility issues:
- the aria-description and language (`<div>`) were added into the `<ul>`, they are added outside the `<ul>` now
- the drag button has no aria-label, it will have now a `aria-labeledby` controlled from clarify
https://app.clickup.com/t/8676zm491
> fix: add `aria-label` on drag handle

- src/components/Tree/TreeItem/TreeItem.tsx
Regression:
bugs #1391 and  #1395 are back after TreeItem refactoring.
When an active tree items is dragged or an inactive item is dragged and goes over an active item, colors are off (see description from original PRs).
> fix: active tree item colors on dragging

- src/components/Checkbox/Checkbox.cy.tsx
- src/components/Checkbox/Checkbox.tsx
https://www.figma.com/file/sNs31nygQIXSfM55RbvS8B/Bulk-Select-Assets?type=design&node-id=875-236497&t=fHKW9xCmM5Knat0Q-4
- Add a checkbox size to be able to have a checkbox of 32px width and height
- Add an emphasis to change the checkbox style (border width, border color) and remove the border when is checked.
> feat: add new emphasis and size to match new design

- src/components/Tree/Tree.tsx
- src/components/Tree/helpers/reducer.spec.cy.tsx
- src/components/Tree/helpers/reducer.ts
identifies whether a node changed its contentComponent props (targets, visibility, etc...)
Otherwise we only check if node IDs match.
> fix(Tree): contentComponent changes update

- src/components/Tree/Tree.tsx
- src/components/Tree/TreeItem/TreeItem.tsx
- src/components/Tree/TreeItem/TreeItemOverlay.tsx
- src/components/Tree/helpers/constants.ts
- src/components/Tree/helpers/index.ts
- src/components/Tree/helpers/projection.ts
- src/components/Tree/utils/keyboardCoordinates.ts
This PR changes the `Tree` component `INDENTATION_WIDTH` constant value from `32` to `20`.
Also, the constants exported on the file `Tree.tsx` were extracted to a `constants.ts` helper file in order to avoid circular dependencies.
> refactor(Tree): change indentation width to 20

- src/components/Tree/Tree.tsx
- src/components/Tree/types.ts
Fixes tree flickering due reloading of the tree when some upper level property gets updated.
`useTransition` on final nodes update seems to hold the re-render until the whole children tree is loaded. Even tested with a 2G throttled network connection.
Without, there is a  re-render when every level gets loaded, leaving the flickering effect.
> fix: Tree flickering

- src/components/ColorPicker/BrandColorPicker.tsx
[Before](https://beta-fondue-components.frontify.com/?path=/story/components-color-picker--with-brand-colors):
Now:
> feat(BrandColorPicker): fix visibility of icons by adding size to segmentControl

- src/components/Tabs/Tabs.tsx
This change stops the propagation of key events to avoid unwanted event bubbling.
> fix(Tab): key navigation stop propagation

- src/components/RichTextEditor/RichTextEditor.tsx
Toolbar should not show up when selecting text in `readonly` mode.
> fix(RTE): disable toolbar in readonly mode

- src/components/Tree/TreeItem/TreeItem.tsx
Fixes draggable area acceptance color and an issue which was freezing the NM in some cases onHover to expand
> fix: Tree expand onHover freeze

- src/components/Tree/TreeItem/TreeItem.tsx
Remove the expand onHover since it's being buggy and unreliable.
> fix: remove buggy expand onHover on Tree

- src/hooks/index.ts
I think the useToggleOverlay is not yet exported from the hooks folder.
> fix(useToggleOverlay): export useToggleOverlay

- src/components/RichTextEditor/RichTextEditor.tsx
- src/components/RichTextEditor/__tests__/RichTextEditor.cy.tsx
- src/components/RichTextEditor/helpers/forceToFocusElement.ts
- src/components/RichTextEditor/helpers/index.ts
Previously on TAB the RTE blurred and removed focus. However TAB should also focus the next element in the focus tree, so in this PR I am implementing that.
> feat(RTE): allow tabbing to next or prev element

- src/components/MenuItem/MenuItem.tsx
The blur, focus and additional mouse events can be used to implement more interactions with MenuItems, other than click. For example, focusing a MenuItem or hovering over it can open a nested menu. 
This is currently not directly possible, since relevant events can only be added the the child nodes.
> feat(MenuItem): Extend props with additional focus, blur and mouse events

- src/components/Tree/TreeItem/TreeItem.tsx
As discussed with Pete, there shouldn't be a background change in the `focus-within` state
> refactor(TreeItem): remove focus-within css

- src/components/Tree/Tree.tsx
This restriction added to prevent extra re-renders before, made Chrome buggy to get level 0 positioning.
Removing it, other previous updates fixed the extra re-renders
> fix: (Tree) remove setOffset restricted update

- src/components/RichTextEditor/__tests__/Rendering.cy.tsx
- src/components/RichTextEditor/__tests__/RichTextEditor.cy.tsx
- src/components/RichTextEditor/utils/parseRawValue.ts
The clickUp task: https://app.clickup.com/t/2523021/TASK-7579
What was braking? when passing text with html  <br /> the RTE was breaking because it creates Nodes without proper parent tag like Paragraph and looked liked this:
```
[{ "text": "\n" }]
```
This made RTE unresponsive and not capable of editing it anymore.
Solution: Wrapping such a text into paragraph parent which is then parsed in correct object for RTE.
Also refactored a bit of test and added new ones for this case.
> fix: updated raw parser [TASK-7579]

- src/components/Tree/TreeItem/TreeItem.tsx
Since the `TreeItem` `onSelect` callback is used by the `Tree` component when cloning the element, we added an `onClick` property for a user defined callback to run after the `onSelect` call.
> refactor(TreeItem): add onClick callback

- src/components/Tree/TreeItem/TreeItem.tsx
When removing all children from a parent, the last child is kept in the UI (as a phantom item). Ensure we unregister them correctly
> fix: Tree clean empty items to prevent phantom items

- src/components/Tree/Tree.tsx
The keydown callback was running for a `TreeItem` children when it is not supposed to, so we will return early if the active item role is not `treeitem`
> fix(Tree): ignore keydown if element is not a tree item

- src/components/Tree/Tree.tsx
The Tree was calling `handleExpand` when pressing the left arrow instead of `handleShrink`.
> fix(Tree): left arrow keydown not collapsing item

- src/components/Tree/TreeItem/TreeItem.tsx
- src/components/Tree/types.ts
`-deeper` suffix on `accepts property indicates that the item can be dropped in deeper levels (grandchildren, grand-grandchildren) so the container item can be expanded.
> feat: Tree only expand on hover for allowed items

- src/components/RichTextEditor/Plugins/ListPlugin/ListItemMarkupElement.tsx
- src/components/RichTextEditor/serializer/utils/serializeNodeToHtmlRecursive.spec.ts
Enforcing `display: list-type` on li elements so it can't be overwritten from the outside
> fix(RTE): list style

- src/components/Tree/TreeItem/TreeItem.tsx
When dragging a selected item hide the selected state to prevent the flashes on/off when you drag past it.
> feat: Tree hide item selected state when dnd

- src/components/Tree/TreeItem/DragHandle.tsx
fixes the Tree drag handler not visible for the active item.
cc: @imoutaharik
> fix: Tree active drag handler visibility

- src/components/Checkbox/Checkbox.tsx
When in `Default` size and `unchecked`, the padding added to the checkbox span was making the container to have `18px` instead of `16px` leading to a content "jump" when checking it.
It is possible to see the problem in https://beta-fondue-components.frontify.com/?path=/story/components-checkbox--checkbox
Just change the state from `Unchecked` to `Checked` or `Mixed`
cc: @imoutaharik
> fix(Checkbox): size changing when unchecked in default size

- src/components/Tree/TreeItem/TreeItem.tsx
decoupling the Tree Item background style allows to control different TreeItems UI states while dragging over.
Now the active item stays visually active even when another item is dragged above
> refactor: Tree item's backgound styling decoupled

- src/components/Tree/helpers/projection.ts
Covering other cases for positioning.
When last item gets pushed out to root level.
> fix: Tree cover more cases on dnd positioning

- src/components/RadioList/RadioList.stories.tsx
- src/components/RadioList/RadioList.tsx
**Issue**
- all RadioList components on a page used the same “name” (default-radio)
- making a selection in one RadioList, changes the selection in another RadioList
- [Reproduction](https://fondue-repros.vercel.app/)
**Solution**
- Added “name” prop 
- Prop is applied as name attribute to all input fields
- The old default value (“default-radio”) for the name of all RadioLists is kept in place in case someone relied on that behavior
**Loom**
https://www.loom.com/share/ff56cd07ebf941e4aadac128b07d6bc7
> feat(RadioList): add name prop

- src/components/Tree/TreeItem/TreeItem.tsx
Tree item with active state is in fact invisible when used in a Flyout, due the background z-index.
This PR fixes the parent positioning and stack to fix the issue.
> fix: (TreeItem) z-index on item w/ active state

- package.json
- pnpm-lock.yaml
@udecode/plate has a peer dependency of slate-react 0.98.2. This resulted in two instances of @udecode/plate installed, one with 0.97.1 and one with 0.98.2. 
This can cause mixups.
> chore(*): bump slate-react

- package.json
Allows TypeScript `moduleResolution` with `Bundler` or `NodeNext` to works
> fix: add `types`

- package.json
- pnpm-lock.yaml
Explicitly add yaml >2.3.2 to solve the high security issue on <=2.2.1
How to rest: `pnpm audit` should not report any critical issue anymore
> chore(deps): update yaml to 2.3.2

- src/components/DatePicker/DatePicker.css
Updating the datepicker package led to introducing breaking styles in the datepicker children container
> chore(datepicker): reset the css for children container

- src/components/DropZone/DropZone.stories.tsx
- src/components/DropZone/DropZone.tsx
- src/components/LegacyOrderableList/LegacyCollectionItem.tsx
- src/components/LegacyOrderableList/LegacyOrderableList.cy.tsx
- src/components/LegacyOrderableList/LegacyOrderableList.stories.tsx
- src/components/LegacyOrderableList/LegacyOrderableList.tsx
- src/components/LegacyOrderableList/index.ts
- src/components/LegacyOrderableList/types.ts
- src/components/LegacyOrderableList/utils/index.ts
- src/components/LegacyOrderableList/utils/mocks.tsx
- src/components/LegacyOrderableList/utils/renderContent.tsx
- src/components/LegacyOrderableList/utils/types.ts
- src/components/index.ts
In order to replace `react-dnd` we need to replace OrderableList, the only component using it.
First step use LegacyOrderableList, this should work the same way as OrderableList
> chore: rename OrderableList to LegacyOrderableList

- src/components/Textarea/Textarea.cy.tsx
- src/components/Textarea/Textarea.stories.tsx
- src/components/Textarea/Textarea.tsx
I added the following props:
- focusOnMount
- onEnterPressed
They behave the same way as in the input component.
I was requiring those props to integrate the textarea into an ongoing feature.
> feat: added focusOnMount and onEnterPressed props to textarea

- src/components/Tree/TreeItem/TreeItem.tsx
Fixes the issue when titles are longer than space available https://app.clickup.com/t/2523021/TASK-8671
Before, the items expands more than parent container hiding elements on the right, like buttons:
After, the ellipsis cuts the text at the right position:
> fix: TreeItem items with longer titles bug

- src/components/Table/Table.tsx
- src/components/Table/TableHeaderRow.tsx
Table header had z-index: 10 in order to avoid being overlaid by table content in mobile view (when the header is sticky). This high z-index value causes it to overlay other elements on the page, such as a sticky header.  The solution should be much less likely to conflict with other elements.
Before:
After:
> fix: table header shouldn't overlay other content

- src/components/RichTextEditor/helpers/exampleValues/exampleValues.ts
- src/components/RichTextEditor/serializer/utils/serializeNodeToHtmlRecursive.spec.ts
- src/components/RichTextEditor/serializer/utils/serializeNodeToHtmlRecursive.ts
[Task](https://app.clickup.com/t/8692pynn1)
Basically the problem was the nesting level was wrongly calculated as it counted all OLs and not just the ones in line. 
- OL
- - SUB OL
- - - SUB SUB OL
- - Another Sub OL
- - - SUB OL
They were all counted and the deepness was 5 but it should have been 3 as that's the deepest and so the wrong numbering was shown
Example of the bug:
How it should be:
> fix(RTE): serializer OL level calculation

- src/components/Tabs/Tabs.tsx
TabItem disabled state
- `text-weak` is overriding the `text-disabled` and we can't see the right color
https://www.figma.com/file/MmTUiRZXSDXtewPb7JYoOg/Metadata-(Permissions-%26-Dependencies)?type=design&node-id=5307-48196&mode=design&t=3c0p2euhnY4rKNTf-0
> fix: apply text disabled text color for the tab label

- src/components/RichTextEditor/Plugins/AutoformatPlugin/index.tsx
- src/components/RichTextEditor/__tests__/RichTextEditor.cy.tsx
added autoformat for legal signs, punctuation, arrows and subscript symbols and numbers, also added autoformat for `1)`
> feat(RTE): add more autoformat options

- src/components/RichTextEditor/Plugins/AutoformatPlugin/index.tsx
- src/components/RichTextEditor/__tests__/RichTextEditor.cy.tsx
Adds the autoformat rule for fractions so 1/2 gets converted to ½
> feat(RTE): add autoformat for fractions

- src/components/Flyout/Flyout.tsx
FocusOnPress causes a lot of issues when using custom components as the trigger element. Preventing focus does nothing to harm accessibility as the button fill be focused natively by the browser.
Everything should still open and close correctly. To see the issue replace the Button component with a standard <button> in the WithButtonFlyoutTemplate and see the focus ring appear when the button is pressed
> fix: prevent focus on press in legacy flyout

- src/components/TextInput/TextInput.tsx
- src/components/Textarea/Textarea.tsx
Fix for `TextInput` and `Teaxtarea` to use `focus` border styling over hover when active.
> fix: Input focus state style hierarchy

- src/components/DatePicker/DatePicker.tsx
Adds ternary operator to `onKeyDown` prop to restrict any external keyboard actions when the calendar is open.
ClickUp Inbox Card
https://app.clickup.com/t/8692mrjv0
> fix: ternary for onKeyDown event when isCalendarOpen

- src/components/Tree/TreeItem/TreeItemMultiselect.tsx
The checkbox is not aligned vertically: https://beta-fondue-components.frontify.com/?path=/story/components-tree-multiselect--multiselect-with-basic-item
In the `MultiselectTreeItem` component there is a `Container` wrapper with `maxWidth="16px"`, we should do the same for that `Container` `maxHeight` prop.
> fix(Tree): Multiselect item checkbox alignment

- src/components/Textarea/Textarea.tsx
Reported here:  https://app.clickup.com/t/8692yd696
`Textarea` cased accessibility issues when nested in a `Accordion`.  It was missing a `focus` handler in the `onClick` event.
> fix(Textarea): add focus on click handler

- src/components/SegmentedControls/SegmentedControls.tsx
Active border not properly aligned in `Segmented Controls`.  This fix adjusts the calculation of its position by removing multiplier and initiated `translateX` value, moving the `motion.div` outside the `Fieldset` and updating the element stying.
Bug Repot: https://frontify.slack.com/archives/C02PSJTPA3D/p1693467213832059
ClickUp: https://app.clickup.com/t/8692mtd17
> fix(SegmentedControls): update element and multipliers to correct active border positions

- src/components/Popper/Popper.tsx
It turns out that our app build has is optimized for production which includes also minification. All of our component names and types have now been minified to something that is completely unpredictable. 
For that purposes I used displayName which we already set and will be the same also in production environment.
> fix: change the type by which are children filtered

- src/components/index.ts
`FormField` missing from group export file.
> fix: add FormField to directory export index

- src/components/Textarea/Textarea.tsx
Fix the focus ring display for Textarea component
- bug can be reproduced on the Libraries sidebar, where fields like description isn't showing the focus ring when focused using the keyboard
> fix(Textarea): show focus ring when using keyboard

- src/components/Accordion/Accordion.tsx
- src/utilities/focusStyle.ts
Update to the `FOCUS_STYLE` properties on the `Accordion` to wrap all elements and not just collapsible content.  
Secondly, because the neighbouring `div` has a `button` child, the focused element needs to be set to `position: relative` to allow for the z-index to take priority and not be overlapped.
Bug Report: https://frontify.slack.com/archives/C02PSJTPA3D/p1689079198399909
ClickUp: https://app.clickup.com/t/862k4a2gm
> fix(Accordion): update focus styling to include header

- src/components/Slider/Slider.tsx
Reported Bug: https://app.clickup.com/t/8692yrx56
Update usability to slider to allow value to increase/decrease when `mouseDown` and `pointer` is outside slider element.
> fix(Slider): change event listeners target

- src/components/SegmentedControls/SegmentedControls.tsx
- src/components/SegmentedControls/Slider.stories.tsx
Reported Bug: https://app.clickup.com/t/8692ztja2
Style logic was not correct and made the active elements `text` color the same as the `bg` color making it invisible.  This corrects this.
> fix(SegmentedControls): correct text color when disabled

- src/components/SegmentedControls/SegmentedControls.tsx
Requested here: [Slack Thread](https://frontify.slack.com/archives/C02PSJTPA3D/p1698238952148359)
> fix(SegmentedControls): refactor active board positioning to avoid z-index

- src/components/SegmentedControls/SegmentedControls.tsx
Reported Bug: https://app.clickup.com/t/8692zxk9b
Active border does not resize one window resize.  This updated the reference of the dimension object to a `state` variable and adds a `useEffect` hook to update the `state` when window is resized.
> fix(SegmentedControls): hook and state to set active border dimensions

- src/hooks/useToggleOverlay.ts
If the component using modal needs to execute sam function at the closing event then this is the callback that can be triggered at closing modal.
I used effect instead of this and it was triggered twice if we use callback is triggered once.
And also removed the function on the 30 line because it is not needed the setAction can be passed directly.
> feat: passed callback prop

- src/components/Tree/Tree.cy.tsx
`Tree` still has one flaky test.  After discovery in Cypress about how to handle nested checks, they recommend using a new `get` call on the parent and then use the `within` callback to check the nested state.
> fix(Tree): update deeper group test to scope check in seperate get call

- .github/lib/lead-time.js
- .github/workflows/comment-lead-time-pr.yaml
Copied from `app-server`, nothing changed. The comment will look like this (https://github.com/Frontify/app-server/pull/17087#issuecomment-1790649857):
---
CU-8692vp9hh - https://app.clickup.com/t/8692vp9hh
> ci: Comment lead time on Pull Request closed

- src/components/TextInput/TextInput.tsx
[Bug Report](https://frontify.slack.com/archives/C02PSJTPA3D/p1699030331837289)
[ClickUp](https://app.clickup.com/t/8693252ef)
`ExtraActions` button spacing pushed button beyond input spacing area.  Looks like a invalid tailwind class was applied.  Removed class and styling renders within boundaries.
> fix(TextInput): remove invalid tailwind class - extra actions

- src/components/TextInput/TextInput.tsx
[Bug Report](https://frontify.slack.com/archives/C02PSJTPA3D/p1698223512499749)
[ClickUp](https://app.clickup.com/t/8692zy02m)
`TextInput` had odd behaviour when text was selected and `mouseDown` held while moving `pointer` up and down (2px shift).  Seems that the tailwind class for `font` size `small` was not correct (`tw-font-s`) and when updated to `tw-font-sm` shift was removed.
> fix(TextInput): update invalid tailwind class for font size

- src/components/Tooltip/index.ts
- src/components/index.ts
Tooltip was not included in the package due to not being exported correctly.
> fix: export tooltip

- src/components/Breadcrumbs/FormattedBreadcrumbs.tsx
Fix `SonarCloud` code smells.  Lexical declarations need to be moved to outside a case block.
> fix(breadcrumbs): move variable declarations outside of case block

- src/components/Tree/TreeItem/TreeItemOverlay.tsx
- src/components/Tree/helpers/sensorsActivationConstraint.tsx
No UI or logic changes. Fixes an issue where Chrome ignores initial dragging an element when it's done quick.
> fix: (Tree) Chrome ignores start dragging

- src/components/NumberInput/NumberInput.stories.tsx
- src/components/NumberInput/NumberInput.tsx
- src/utilities/input.tsx
[ClickUp](https://app.clickup.com/t/8693a8auu)
Action buttons were clickable on  `disabled` and `readOnly` states.  This fixes this, as well as updates styles to the `InputStyles` object and the `clearable` button to shared `InputActions` component
> fix(NumberInput): update shared input references and disabled state

- src/components/LegacyTextarea/LegacyTextarea.stories.tsx
- src/components/LegacyTextarea/LegacyTextarea.tsx
- src/components/index.ts
`Textarea` directory export was left out of main `index` file
> fix(Textarea): add export to component main index

- src/components/Textarea/Textarea.cy.tsx
- src/components/Textarea/Textarea.stories.tsx
- src/components/Textarea/Textarea.tsx
`defaultValue` and `value` props were not being properly set.  This updates the usage and logic of these two props and the stories to use them properly.
> fix(Textarea): update defaultValue and value props logic and stories

- .github/CODEOWNERS
This change removes the Design System team from `CODEOWNERS` as it's no longer set up as such.
> chore: remove design system team

- src/components/LegacyOrderableList/LegacyCollectionItem.tsx
- removed "labelledby" attribute
The `labelledby` attribute does not make sense on this component as it refernces just an random Id wich doesn't exist anywhere in it's subcomponents. Removing it doesn't change it's accessibility, but gets rid of the forbidden usage warning.
> fix: [TASK-9408] removed unused aria attribute

- src/components/RichTextEditor/EditorPositioningWrapper/ToolbarWrapper/ToolbarWrapperPositioningBottom.tsx
- src/components/RichTextEditor/EditorPositioningWrapper/ToolbarWrapper/ToolbarWrapperPositioningFloating.tsx
- src/components/RichTextEditor/EditorPositioningWrapper/ToolbarWrapper/ToolbarWrapperPositioningTop.tsx
also on marketplace
Somehow the `.tw-min-h-12` wasn't included in the bundle before
> fix(RTE): toolbar height is too big

- src/components/AssetInput/SingleAsset/SelectedAsset.tsx
- src/components/Breadcrumbs/FormattedBreadcrumbs.tsx
- src/components/InlineDialog/InlineDialog.stories.tsx
- src/components/Menu/Menu.tsx
- src/components/MultiSelect/MultiSelect.tsx
- src/components/Switch/Switch.tsx
- asset picker
- Added a role to the element
- inline dialog trigger
- Added a Aria Label to the Provided Trigger in the story
- menu
- removed unnecessary role
- switch
- added customizable aria label
- breadcrumbs
- replaced "empty" element span by li
- multiselect
- fix role
> fix: A11y Issues

- packages/fondue/src/components/RichTextEditor/Plugins/GeneratePlugins.tsx
- packages/fondue/src/components/RichTextEditor/RichTextEditor.tsx
- packages/fondue/src/components/RichTextEditor/components/RenderPlaceholder/RenderPlaceholder.tsx
- packages/fondue/src/components/RichTextEditor/components/RenderPlaceholder/index.ts
- packages/fondue/src/components/RichTextEditor/context/EditorResizeContext.tsx
- packages/fondue/src/components/RichTextEditor/context/RichTextEditorContext.tsx
- packages/fondue/src/components/RichTextEditor/hooks/useEditorState.ts
- packages/fondue/src/components/RichTextEditor/utils/InitPlateEditor.ts
- packages/fondue/src/hooks/useDebounce.ts
Reduce the amount of time spent in rendering the RichTextEditor by approximately 20% through memoizing props:
To test:
Copy this code block and run in a storybook iframe for a good indication of the differences.
```
const RichTextEditorTemplate: StoryFn<RichTextEditorProps> = (args: RichTextEditorProps) => {
const [readonly, setReadonly] = useState(false);
return (
<>
<button onClick={() => setReadonly((r) => !r)}>Click {readonly ? 'on' : 'off'}</button>
<RichTextEditorComponent {...args} readonly={readonly} />
<RichTextEditorComponent {...args} readonly={readonly} />
<RichTextEditorComponent {...args} readonly={readonly} />
<RichTextEditorComponent {...args} readonly={readonly} />
<RichTextEditorComponent {...args} readonly={readonly} />
<RichTextEditorComponent {...args} …
```
> feat: performance improvements

- packages/fondue/src/components/Tooltip/Tooltip.tsx
Bug report by @ryancarville 
When the tooltip switches to `disabled` while open, it gets stuck in the open state.
Removing the condition to check for disabled when closing the tooltip.
> fix: Allow closing tooltip when it's disabled

- .changeset/gold-dragons-compare.md
- packages/fondue/src/components/RichTextEditor/BlurObserver.ts
- packages/fondue/src/components/RichTextEditor/Plugins/LinkPlugin/FloatingLink/EditLinkModal/EditModal.tsx
- packages/fondue/src/components/RichTextEditor/Plugins/LinkPlugin/FloatingLink/InsertLinkModal/InsertModal.tsx
- packages/fondue/src/components/RichTextEditor/components/FloatingModal/FloatingModal.tsx
- packages/fondue/src/components/RichTextEditor/components/FloatingModal/index.ts
Fixes an issue where toolbar flyouts would remain open when the user clicked a different spot inside the RichTextEditor.
Also reduces the number of calls and the complexity of the blur observer by only activating it when the editor is in focus.
Linked pr: https://github.com/Frontify/brand-sdk/pull/803
How to test with a guideline-block:
To be sure that you are using local code add a console.log() to the RTE component. (It will only show in edit mode since view mode uses the serialized html)
In @frontify/fondue
```
pnpm link --global
pnpm build
```
In @frontify/brand-sdk
```
rm -rf node_modules/.vite && rm -rf packages/guideline-blocks-settings/node_modules/.vite && pnpm build 
cd packages/guideline-blocks-settings
pnpm link --global
cd ../app-bridge
pnpm link --global
```
In …
> fix(RichTextEditor): flyout modals not closing when clicked outside

- .github/CODEOWNERS
This PR introduces a stricter CODEOWNERS configuration to elevate the ownership level of the Frontend Platform Team across all files.
This will help ensure consistency in PR reviews and prevent against unexpected breaking changes.
If successful, this PR should already display a codeownership review.
> chore: setup default owner for project in codeowners

- .changeset/lucky-rivers-doubt.md
- packages/fondue/src/components/FormField/FormField.cy.tsx
- packages/fondue/src/components/Tooltip/Tooltip.cy.tsx
- packages/fondue/src/components/Tooltip/Tooltip.stories.tsx
- packages/fondue/src/components/Tooltip/Tooltip.tsx
In tooltip replaced mouse events with pointer events to have control over tooltip and dont show it on touch devices if the type of it is touch or pen. Only show it when pointer type is mouse.
> fix: replaced mouse events with pointer events

- src/components/InlineDialog/InlineDialog.cy.tsx
- src/components/InlineDialog/InlineDialog.stories.tsx
- src/components/InlineDialog/InlineDialog.tsx
Conversation behind the changes in [this PR](https://github.com/Frontify/fondue/pull/1755)
> chore: added unsafe_zIndex property to `InlineDialog`

- .changeset/five-moons-teach.md
- packages/fondue/src/components/Tree/TreeItem/TreeItemMultiselect.tsx
- packages/fondue/src/components/Tree/utils/mocks.ts
Issue: disabled items get selected and disabled when selecting a parent.
The intention of this PR is not showing as selected a disabled item, it's confusing and misleading.
> feat: disabled items unchecked on multiselect tree

- .changeset/twelve-cars-lie.md
- packages/fondue/src/components/RichTextEditor/Plugins/TextStylePlugin/TextStyleDropdown/useSelectedTextStyles.ts
- packages/fondue/src/components/RichTextEditor/__tests__/RichTextEditor.cy.tsx
Try with
```
{
"type": "heading1",
"children": [{
"text": "Sample text"
}]
}
```
Text style dropdown should show heading1 but it doesn't.
> fix(RTE): text style dropdown shows wrong value

- .changeset/gentle-dots-drum.md
- packages/fondue/src/components/ActionMenu/ActionMenu/ActionMenu.cy.tsx
- packages/fondue/src/components/ActionMenu/ActionMenu/ActionMenu.tsx
- packages/fondue/src/components/ActionMenu/Aria/AriaMenuItem.tsx
TASK-10958
Deprecate the `ActionMenu` level `onClick`. (I'm not exactly sure why this was added but there were no instances of it's usage that I could find).
By adding the `onClick` command to the `mergeProps` function it is added to a chain of functions, instead of overwriting the internal `onClick` provided by `useMenuItem`.
This fixes an issue where touch-to-click commands were not recognised by the `ActionMenu`
> fix: prevent overwrite of onClick

- .github/workflows/charts-pull-requests.yaml
- .github/workflows/continuous-deployment.yaml
- .github/workflows/docs-pull-requests.yaml
- .github/workflows/fondue-pull-requests.yaml
- .github/workflows/pull-request-security-audit.yaml
- package.json
So [this](https://github.com/Frontify/fondue/actions/runs/8968679284/job/24628597757?pr=1855) (the ci) should not fail anymore, as it should use the pnpm version defined in the `package.json`
After discussion with @noahwaldner also bumping `pnpm` to `9.1.0`
> ci: should use pnpm version defined in package.json

- .changeset/seven-actors-greet.md
- packages/components/tailwind.config.ts
- packages/fondue/tailwind.config.ts
If you want to add an additional small breakpoint, you can’t use extend because the small breakpoint would be added to the end of the breakpoint list
https://tailwindcss.com/docs/screens#adding-smaller-breakpoints
> fix: tailwind config: override the entire screens key for the right order of breakpoints

- .changeset/unlucky-waves-shop.md
- packages/components/src/components/Button/Button.tsx
- packages/components/src/components/Button/styles/buttonStyles.ts
- packages/components/src/components/Checkbox/Checkbox.tsx
- packages/components/src/components/Checkbox/styles/checkboxStyles.ts
- packages/components/src/components/SegmentedControl/SegmentedControl.tsx
- packages/components/src/components/SegmentedControl/styles/segmentedControlStyles.ts
- packages/components/src/components/TextInput/TextInput.tsx
- packages/components/src/components/TextInput/__tests__/TextInput.ct.tsx
- packages/components/src/components/TextInput/styles/textInputStyles.ts
- packages/components/src/utilities/focusStyle.ts
This change adds our global focus ring to all components.
The TextInputField is handled manually, because text input elements behave differently with `:focus-visible`
> feat: add focus outline for all components

- .changeset/lovely-frogs-judge.md
- packages/components/src/utilities/focusStyle.ts
In vitest, the component double quote makes the rest of the class unescaped and interpreted as props
`class="focus-visible:tw-outline has-[[data-show-focus-ring="true"]]:tw-outline tw-outline-4"` is going to be rendered as
`class="focus-visible:tw-outline has-[[data-show-focus-ring=" true="" :tw-outline="" tw-outline-4=""`
> fix: remove double quote breaking tests

- .changeset/gentle-crabs-report.md
- packages/fondue/src/components/RichTextEditor/Plugins/ColumnBreakPlugin/createColumnBreakPlugin.ts
- packages/fondue/src/components/RichTextEditor/Plugins/ColumnBreakPlugin/types.ts
- packages/fondue/src/components/RichTextEditor/Plugins/Plugin.ts
- packages/fondue/src/components/RichTextEditor/RichTextEditor.tsx
- packages/fondue/src/components/RichTextEditor/__tests__/RichTextEditor.cy.tsx
This PR adds `customClass` to the `ColumnBreakPlugin`.
With this addition, you can create the plugin like this:
`new BreakAfterPlugin({ customClass: 'tw-columns-1 @sm:tw-columns-2' })`
This allows more fine-grained controls when needed while keeping the original implementation as well.
> feat(RTE): add custom class to column break plugin

- .changeset/smart-dolphins-look.md
- packages/fondue/src/typography/Text/Text.tsx
- packages/fondue/src/typography/shared/records.ts
- packages/fondue/src/typography/shared/types.ts
Added additional prop to whitespace typography because the others are interfering with trucate and clamp over multiple lines. If you set nowrap then you have troubles with breakpoints and cant change without hack.
https://www.loom.com/share/b05eb765afb947899a757bcd1ff1d834?sid=7d50273f-aba6-41ea-8ce8-ab53fde96527
> feat: added `whitespace="unset"` to the Text props

- .changeset/old-walls-invent.md
- packages/fondue/package.json
- pnpm-lock.yaml
`@udecode/plate-common` is an implicit dependency, however when trying to bump fondue in other packages, the `@udecode/plate-common` dependency resolves to `34.0.0` instead of `31.3.2` which causes a bunch of typeerrors.
[Example](https://github.com/Frontify/brand-sdk/actions/runs/9598422554/job/26469694277?pr=976)
> chore: add @udecode/plate-common dependency explicitly

- .changeset/button-outline-firefox-fix.md
- packages/components/src/utilities/focusStyle.module.scss
- packages/components/src/utilities/focusStyle.ts
This here global style is given priority over the class declaration that assigns the proper outline. This is a firefox specific declaration that sets `outline:auto` and seems to be coming from [tailwind's normalization styles](https://cdn.frontify.com/css/spa-frontify-index.7dcb291c092af233ee86.css). The `currentcolor` definition basically inherits from the button's text color, which in some cases will match the background color where the button is located (ie. if the button is black with white text on white background) giving the impression that no outline is present. By making the class declaration more specific the issue is fixed.
[CU-869519gyp](https://app.clickup.com/t/869519gyp)
> fix: prevent firefox from overriding outline class with global pseudo class def

- .changeset/many-dingos-hug.md
- packages/fondue/src/components/Table/Table.cy.tsx
- packages/fondue/src/components/Table/Table.stories.tsx
- packages/fondue/src/components/Table/Table.tsx
- packages/fondue/src/components/Table/TableCell.tsx
- packages/fondue/src/components/Table/TableColumnHeader.tsx
Also updated stories and tests
> feat: table - add column align props and custom title node for column headers

- .changeset/two-ants-lick.md
- packages/fondue/scripts/generateReactIcons.ts
- packages/fondue/src/components/Accordion/AccordionHeaderIcon.tsx
Clickup task: [2523021/TASK-11732](https://app.clickup.com/t/2523021/TASK-11732)
This should fix an array of issues for screen readers stumbling into icons and confusing users but it was done in light of an issue reported in respect to the accordion.
> fix: remove accordion's empty aria-labelledby, add aria-hidden to icon generator

- .changeset/healthy-tips-kick.md
- packages/fondue/src/components/Tree/TreeItem/TreeItem.tsx
Added `forwardRef` to `TreeItem` to enable having a ref to its top-level `<li />`  from the outside.
Rest of the changes are indentation.
> feat: add forwardRef to TreeItem component

- .changeset/brave-masks-argue.md
- packages/fondue/src/components/Checkbox/Checkbox.tsx
- packages/fondue/src/components/Checklist/Checklist.tsx
- packages/fondue/src/components/MultiSelect/MultiSelect.tsx
Clickup task: [2523021/TASK-10714](https://app.clickup.com/t/2523021/TASK-10714)
I went ahead and enabled arrow navigation without too much fanciness (no multi directional stuff), it should be enough to make this usable. 
For the life of me I can't get the keyboard nav tests to work here and since this didn't have any of those before and we'll replace this component soon anyway maybe we can let it slide.
> fix: MultiSelect component not a11y compliant

- .changeset/shy-jeans-rescue.md
- packages/components/src/helpers/layout.module.scss
wrap the declerations in `$ {}` to get rid of the deprecation warning in the new sass version
> fix: fix sass deprecation warning

- .changeset/kind-ears-divide.md
- packages/charts/src/components/BarChart/BarChart.stories.tsx
- packages/charts/src/components/BarChart/BarChart.tsx
- packages/charts/src/components/BarChart/components/Axes.tsx
- packages/charts/src/components/BarChart/types.ts
- packages/charts/src/components/common/components/Tooltip/Tooltip.spec.tsx
- packages/charts/src/components/common/components/Tooltip/Tooltip.tsx
- packages/charts/src/components/common/components/Tooltip/TooltipContent.tsx
- packages/charts/src/components/common/components/Tooltip/helpers/getTooltipEntries.spec.ts
- packages/charts/src/components/common/components/Tooltip/helpers/getTooltipEntries.ts
> feat(bar chart): tooltip changes [CU-8695881ux]

- .changeset/friendly-pots-kiss.md
- packages/charts/src/components/BarChart/BarChart.stories.tsx
- packages/charts/src/components/BarChart/BarChart.tsx
- packages/charts/src/components/BarChart/types.ts
- packages/charts/src/components/LineChart/LineChart.stories.tsx
- packages/charts/src/components/LineChart/types.ts
- packages/charts/src/components/common/components/Tooltip/Tooltip.spec.tsx
- packages/charts/src/components/common/components/Tooltip/Tooltip.tsx
- packages/charts/src/components/common/components/Tooltip/TooltipContent.tsx
- packages/charts/src/components/common/components/Tooltip/helpers/getTooltipEntries.spec.ts
- packages/charts/src/components/common/components/Tooltip/helpers/getTooltipEntries.ts
A more granular approach was needed to fill the requirements of the new tooltip, dropped the `valueContextBySeries` and passed the value along with the data point, which is rendered by the tooltip.
Examples: 
Design:
> refactor: tooltip value context approach [CU-8695b2cv6]

- .changeset/smooth-chicken-marry.md
- packages/components/src/components/Flyout/Flyout.stories.tsx
- packages/components/src/components/Flyout/Flyout.tsx
- packages/components/src/components/Flyout/__tests__/Flyout.ct.tsx
- packages/components/src/components/Flyout/styles/flyout.module.scss
See the brand selector flyout [here](https://www.figma.com/proto/Zl26s5HJwNnS5O3fIgSaIF/Navigation-Quest---Design?page-id=1305%3A67976&node-id=1350-105611&viewport=16687%2C-19673%2C1.15&t=WCYgD2268pO9rHXt-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1350%3A105612) and check the hover effects on the elements. A tighter spacing is needed to achieve this.
> feat: add flyout padding option "tight"

- .changeset/blue-doors-hammer.md
- packages/components/src/components/Flyout/Flyout.stories.tsx
- packages/components/src/components/Flyout/Flyout.tsx
- packages/components/src/components/Flyout/__tests__/Flyout.ct.tsx
handle focusing of interactive elements inside of a Flyout
- Don't show focus visible when opened with mouse
> feat: handle focusing of interactive elements inside of a Flyout

- .changeset/flat-windows-brake.md
- packages/fondue/src/components/CollapsibleWrap/CollapsibleWrap.tsx
To avoid scenarios like this I set the overflow to visible after the animation is done.
> fix(CollapsibleWrap): overflow is kept hidden after expansion

- .changeset/rotten-poems-guess.md
- packages/charts/src/components/PieChart/components/Label.tsx
> fix(charts): pie chart label overlapping [CU-86930eter]

- .changeset/late-mirrors-kiss.md
- packages/charts/src/components/BarChart/BarChart.stories.tsx
- packages/charts/src/components/BarChart/types.ts
- packages/charts/src/components/common/components/Tooltip/Tooltip.spec.tsx
- packages/charts/src/components/common/components/Tooltip/Tooltip.tsx
- packages/charts/src/components/common/components/Tooltip/TooltipContent.tsx
> feat(charts): add support for image rendering inside tooltip

- .changeset/rude-dolls-add.md
- packages/fondue/src/components/Table/TableColumnHeader.tsx
> feat: table - align column header styles

- .changeset/shy-deers-enjoy.md
- packages/components/src/components/TextInput/TextInput.tsx
Noticed a type issue when migrating the common text input component and I believe it is a genuine bug with our text input stemming from incorrect types on these callbacks
> fix(TextInput): update types

- .changeset/young-owls-invent.md
- packages/components/MIGRATING.md
- packages/components/src/components/Table/Table.stories.tsx
- packages/components/src/components/Table/Table.tsx
- packages/components/src/components/Table/__tests__/Table.ct.tsx
- packages/components/src/components/Table/__tests__/utils.spec.ts
- packages/components/src/components/Table/styles/table.module.scss
- packages/components/src/components/Table/utils.ts
- packages/components/src/hooks/useSyncRefs.ts
- packages/components/src/hooks/useTextTruncation.ts
- packages/components/src/utilities/domUtilities.ts
> feat(Table): refactor component

- .changeset/healthy-melons-enjoy.md
- packages/components/.storybook/components/DecorativeContent.tsx
- packages/components/src/components/Box/Box.tsx
- packages/components/src/components/Flex/Flex.tsx
- packages/components/src/components/Grid/Grid.tsx
- packages/components/src/components/Section/Section.tsx
Prevents warning (component uses unknown attributes) as it would spread all props including `mx`, `gap`, ...
> fix: don't spread customization props alongside aria

- .changeset/honest-hounds-work.md
- packages/charts/src/components/common/components/Tooltip/TooltipContent.tsx
Tooltips with long, single word (with dashes or underscores) titles look strange when the template preview image is shown. (_See the image below for an example from Superheroes_).
This PR fixes the issue by adding a max-width, and setting the image to full width. It also includes an update to truncate the description lines (in this case Brand, Project, etc.) as requested by our team's designer.
Before:
After:
> feat: add max-width and adjust styling of tooltip image and description text

- .changeset/silver-chicken-whisper.md
- packages/charts/src/components/common/components/Tooltip/TooltipContent.tsx
Set tooltip description word-break property to 'all'. See [this PR](https://github.com/Frontify/fondue/pull/2115) for additional context.
> feat: set tooltip description word-break property to 'all'

- .changeset/early-avocados-heal.md
- .changeset/five-moons-remember.md
- packages/components/src/components/Table/Table.tsx
- packages/components/src/components/Table/styles/table.module.scss
- packages/components/src/components/TextInput/styles/text.module.scss
- make sure `:-moz-focusring` is overridden to avoid double outlines
- fix aligning content in table cells when sorting is present
- fix text truncation when sorting is present
CU-86970tv1f
CU-86971xjcy
> fix: issues with table alignment + focus rings

- .changeset/tough-suns-lick.md
- packages/components/src/components/Flyout/styles/flyout.module.scss
- packages/components/src/utilities/focusStyle.module.scss
- use custom outline on flyout
- adjust focus-outline mixin to only appear when a direct child is focused
> fix: improve handling of focus outline on flyout

- .changeset/cuddly-rice-kneel.md
- packages/components/src/components/Button/Button.tsx
If the button is outside of a form, devs won't be able to make it submit that form.
> feat(Button): add `form` prop 

- .changeset/wet-otters-press.md
- packages/components/src/components/Button/styles/buttonStyles.ts
> fix(Button): buttons within table cells are overflowing container

- .changeset/gentle-insects-smile.md
- packages/components/src/components/Dialog/Dialog.stories.tsx
- packages/components/src/components/Dialog/Dialog.tsx
- packages/components/src/components/Dialog/__tests__/Dialog.ct.tsx
- packages/components/src/components/Dialog/styles/dialog.module.scss
> fix(Dialog): missing granular padding control

- .changeset/rotten-sheep-study.md
- packages/components/src/components/TextInput/TextInput.stories.tsx
- packages/components/src/components/TextInput/styles/text.module.scss
> fix: text input success/error icon margin if no decorator

- .changeset/stupid-beers-travel.md
- packages/components/src/components/Switch/styles/switch.module.scss
Props: disabled: `true`, value: `true`
Before:
https://github.com/user-attachments/assets/d45a83e4-9ffd-477b-a587-cfb889aac1df
After: 
https://github.com/user-attachments/assets/34e02dfe-28a3-4229-9fb5-e4dcaa4abd03
> fix: remove hover state when switch is disabled and toggled

- .changeset/little-experts-cheer.md
- packages/components/src/components/ColorPicker/styles/customColorPicker.module.scss
Container width 310px:
Container width <310px
> fix: make ColorPicker inputs responsive based on container size

- .changeset/nasty-icons-work.md
- packages/components/src/components/Button/Button.tsx
> fix: prevent `hugWidth` from being spread on the `button`

- .changeset/tender-days-lie.md
- packages/components/src/components/Dialog/__tests__/Dialog.ct.tsx
- packages/components/src/components/Dialog/styles/dialog.module.scss
> fix(Dialog): content not expanding dialog properly

- .changeset/dry-days-rest.md
- packages/charts/.storybook/preview.ts
- packages/charts/src/index.css
- packages/fondue/.storybook/preview.tsx
- packages/fondue/cypress/support/component.ts
- packages/fondue/src/styles.css
The tokens should not be bundled with the components.
They can be mad available by separately importing `import '@frontify/fondue-tokens/styles'` or wrapping in a `ThemeProvider`
> fix: remove tokens from the css bundles

- .changeset/smooth-hounds-relax.md
- packages/fondue/src/subpackages/tokens.js
FIX: Solves issue of dark theme not working inside of terrific components
Add the dark theme to the legacy style export used by some terrific components
CU-8697vk44j
> fix: add legacy export for dark theme

- .changeset/friendly-olives-drum.md
- packages/components/src/components/Table/styles/table.module.scss
Explicitly set box sizing for header cell to avoid overflow.
If in the place of usage a parent selector for `box-sizing: content-box is present`, it currently causes a overflow issue
CU-8697wnkzm
> fix: define box sizing for Table Header Cell

- .changeset/hungry-jokes-search.md
- packages/components/src/components/ScrollArea/ScrollArea.stories.tsx
- packages/components/src/components/ScrollArea/ScrollArea.tsx
- packages/components/src/components/ScrollArea/__tests__/ScrollArea.ct.tsx
- packages/components/src/components/ScrollArea/styles/scrollArea.module.scss
CU-8697y5qxd
It can be rather annoying using scroll areas inside elements like Dialogs because you have to cancel the padding on the dialog and then use tailwind to recreate it. This way we get some convenience while not sacrificing on composibility
> feat(ScrollArea): add padding options

- .changeset/slow-poems-beg.md
- packages/components/src/components/Flyout/styles/flyout.module.scss
Adding the `ThemeProvider` makes this not be a direct child of the `body`
> fix: fix broken flyout width on mobile

- .changeset/young-plants-exist.md
- packages/components/src/components/Dialog/styles/dialog.module.scss
> fix(Dialog): dialog height grows too much on safari

- .changeset/khaki-donuts-behave.md
- packages/components/src/components/Table/styles/table.module.scss
> fix(Table): make sure focus ring on table is always on top

- .changeset/old-ways-roll.md
- packages/components/src/components/ColorPicker/ColorPicker.stories.tsx
- packages/components/src/components/ColorPicker/ColorPicker.tsx
- packages/components/src/components/ColorPicker/ColorPickerInput.tsx
- packages/components/src/components/ColorPicker/styles/colorInput.module.scss
- packages/components/src/components/ColorPicker/utils.ts
- pass slot props from flyout to button instead of div to resolve a11y issues
- fix issue where opacity 0 was transformed into opacity 1
- added functionality to control the format externally
- added check pattern background for the color preview in the input to make transparency more visible
- display rgba value when no name is passed for the coolor
CU-8698kmet7
CU-8698j7gdf
> fix: adress color picker issues

- .changeset/mighty-news-unite.md
- packages/components/src/components/SegmentedControl/SegmentedControl.tsx
- packages/components/src/components/SegmentedControl/__tests__/SegmentedControl.ct.tsx
This PR adds type generic capabilities to the SegmentedControl component, allowing for stronger type safety when working with enum values and string literal types.
before
```tsx
<SegmentedControl.Root
value={visibility}
defaultValue={VisibilityKind.Visible}
onValueChange={_value => {
const value = _value as VisibilityKind; // Type assertion needed 😢
// ...
}}
>
{/* ... */}
</SegmentedControl.Root>
```
after
```tsx
<SegmentedControl.Root<VisibilityKind> // passing the generic is optional
value={visibility}
defaultValue={VisibilityKind.Visible}
onValueChange={value => {
// TypeScript knows 'value' is VisibilityKind! 🎉
// ...
}}
>
{/* ... */}
</SegmentedControl.Root>
```
This component enhancement maintains full backward compatibility. You can continue using <SegmentedControl.Root> without …
> feat: add generic type support to `SegmentedControl` component

- .changeset/upset-glasses-rule.md
- packages/components/src/components/Flyout/Flyout.tsx
- packages/components/src/components/Flyout/__tests__/Flyout.ct.tsx
- packages/components/src/components/Flyout/styles/flyout.module.scss
CU-86994t2ye
bug reported in LibraryList
Clicking outside the Flyout should not trigger things outside, instead it should only close the Flyout. 
(having this issue right now in Library list.)
> fix: Clicking outside flyout not triggering other elements

- .changeset/modern-rivers-strive.md
- packages/components/src/components/Table/Table.stories.tsx
- packages/components/src/components/Table/Table.tsx
- packages/components/src/components/Table/__tests__/Table.ct.tsx
- packages/components/src/components/Table/__tests__/utils.spec.ts
- packages/components/src/components/Table/utils.ts
**What:**
This PR fixes how clicks work in the `<Table.Row>` component.
If the `click` prop is defined for <Table.Row>:
- clicking a button or link inside a cell will only trigger that button or link’s click
- clicking on a cell without a button or link will trigger the row’s click.
**Why:**
Previously, clicks on interactive elements like buttons or links inside a table row would also fire the row’s click handler.
> fix: prevent button and link clicks inside <Table.Row> from triggering row click

- .changeset/new-poets-stay.md
- packages/charts/src/components/AreaStackChart/AreaStackChart.tsx
- packages/charts/src/components/BarChart/BarChart.tsx
- packages/charts/src/components/LineChart/LineChart.stories.tsx
- packages/charts/src/components/LineChart/LineChart.tsx
- packages/charts/src/components/common/components/Tooltip/Crosshair.tsx
- packages/charts/src/components/common/components/Tooltip/Tooltip.tsx
> fix(charts): crosshair overlap [CU-869a89rkf]

- .changeset/little-cobras-join.md
- packages/components/src/components/Dialog/Dialog.tsx
- packages/components/src/components/Dialog/__tests__/Dialog.ct.tsx
- packages/components/src/components/Tooltip/Tooltip.tsx
\+ removal of the spread since they are usually empty objects.
Prevents issues like this 
https://github.com/user-attachments/assets/8a0603ef-bde9-4cf1-ab27-41a2b25688cd
> fix: prevent tooltip focus when opening dialogs

- .changeset/crazy-walls-mate.md
- packages/components/src/components/Tag/styles/tag.module.scss
> chore(Tag): fix focus ring visibility
