- src/compositions/ButtonGroup/ButtonGroup.spec.tsx
- src/elements/Button/Button.tsx
Clickup Ticket: https://app.clickup.com/t/nxe9ak
> fix(Button): height and icon offset

- src/compositions/Accordion/Accordion.stories.tsx
- src/compositions/Accordion/Accordion.tsx
- src/compositions/FieldsetHeader/FieldsetHeader.tsx
Clickup Ticket: https://app.clickup.com/t/nq8yxx
> fix(Accordion): animation and styling fixes

- src/components/Tooltip/Tooltip.spec.tsx
- src/components/Tooltip/Tooltip.tsx
- src/elements/Checkbox/Checkbox.spec.tsx
- src/elements/Checkbox/Checkbox.tsx
Clickup Ticket: https://app.clickup.com/t/pq8qe3
TODO: add Tooltip focus styles
> fix(Checkbox): scale and tooltip aria

- src/components/Dropdown/Dropdown.tsx
- src/components/Slider/Slider.tsx
- src/elements/Checkbox/Checkbox.tsx
- src/elements/Switch/Switch.stories.tsx
- src/elements/Switch/Switch.tsx
- src/elements/TextInput/TextInput.tsx
- src/elements/Textarea/Textarea.tsx
Clickup Ticket: https://app.clickup.com/t/pxc57g
> fix(Switch): add label layout prop and fix form control ids

- src/components/Breadcrumbs/Breadcrumbs.spec.tsx
- src/components/Breadcrumbs/Breadcrumbs.stories.tsx
- src/components/Breadcrumbs/Breadcrumbs.tsx
- src/components/Breadcrumbs/CurrentBreadcrumbItem.tsx
Clickup Ticket: https://app.clickup.com/t/nq8yaa
TODO: add focus styles
> fix(Breadcrumbs): add onClick and fix hover

- src/elements/AddBlockButton/AddBlockButton.spec.tsx
- src/elements/AddBlockButton/AddBlockButton.tsx
Applies the focus styling to AddBlockButton.
I was just playing around to understand the new architecture, but if it all goods then you may as well have it so you don't need to do it yourself. Might save you all of 5 minutes ;).
If it's too much of a mess then just throw it out. I won't be offended.
> feat(Add Block Button): Add focus style

- src/compositions/FormControl/FormControl.stories.tsx
This PR adds a storybook story for the `FormControl` component with a vertical checklist.
> Feat(Form Control): add story with checklist

- src/elements/TextInput/TextInput.tsx
This PR adds a few improvements to the TextInput component.
- Add hover effect on the clear input button
- Add hover effect on the password show/hide button
- Add correct styles when the clear and password show/hide buttons are focused using a keyboard
- Remove the forbidden cursor on hover when input is disabled
- Refactoring to reduce complexity
> feat(TextInput): Improve component

- src/components/Menu/MenuItem/MenuItemContent.tsx
Ticket: https://app.clickup.com/t/1jz4yck
> fix(Dropdown): Apply Smaller Gap for Small MenuItem

- src/elements/Switch/Switch.tsx
This PR is an attempt at reducing conditionals complexity by extracting out the line and dot classes to dedicated functions.
> refactor: reduce switch component render complexity

- src/elements/Checkbox/Checkbox.tsx
- src/elements/InputLabel/InputLabel.tsx
addresses this ticket: https://app.clickup.com/t/1k529k5
> fix: add group-hover for checkbox and label

- src/components/ColorInputFlyout/ColorPickerTrigger.tsx
- src/components/Menu/ActionMenu/ActionMenu.tsx
- src/components/MenuItem/MenuItemContent.tsx
Concerns this ticket: https://app.clickup.com/t/1m79v6g
> fix: ColorPickerTrigger title style

- src/components/Table/TableColumnHeader.tsx
Concerns this ticket: https://app.clickup.com/t/1mrcgrz
> fix: table select all

- src/components/ColorInputFlyout/ColorPickerFlyout.spec.tsx
- src/components/ColorPicker/BrandColorPicker.tsx
- src/components/ColorPicker/ColorPicker.spec.tsx
- src/components/ColorPicker/ColorPicker.tsx
- src/types/colors.ts
- src/utilities/colors.ts
Labels can be identical, this fixes the issue by using ids
> fix(ColorPicker): use id as `key`

- src/components/ColorInputFlyout/ColorInputTitle.tsx
- src/components/ColorInputFlyout/ColorPickerFlyout.tsx
- src/components/ColorInputFlyout/ColorPickerTrigger.tsx
- src/components/ColorPicker/BrandColorPicker.tsx
- src/components/ColorPicker/ColorPicker.spec.tsx
- src/components/ColorPicker/ColorPicker.stories.tsx
- src/components/ColorPicker/ColorPicker.tsx
- src/components/ColorPicker/CustomColorPicker.tsx
- src/types/colors.ts
- src/utilities/colors.ts
Concerns the last three checklist items in this ticket: https://app.clickup.com/t/1m79v6g
> fix: color input trigger title and preview color, setFormat in ColorPicker

- src/components/FormControl/FormControl.tsx
This PR fixes the missing spacing in lists wrapped in the FormControl component.
https://app.clickup.com/t/yyc0fd
> fix: spacing in FormControl nested lists

- src/components/Accordion/Accordion.tsx
Fixes https://app.clickup.com/t/1vc80g2
> fix: input focus in accordion

- src/foundation/Icon/Icon.stories.tsx
This PR adds the ability for icons to turn white on dark mode.
> Turn icons to white on dark mode

- src/components/MenuItem/MenuItemContent.tsx
> style: hide overflow on y axis

- src/components/Dropdown/Dropdown.spec.tsx
- src/components/Dropdown/Dropdown.tsx
- src/foundation/Icon/Generated/index.ts
Added a resize event to automatically recalculate divider height
> fix(dropdown): add automatic resize listener

- src/components/ColorPicker/ColorInput.tsx
- src/components/ColorPicker/CustomColorPicker.tsx
Clickup ticket: https://app.clickup.com/t/nq8zf6
> fix(color-picker): update hex when enter is pressed

- src/components/TextInput/TextInput.spec.tsx
- src/components/TextInput/TextInput.stories.tsx
- src/components/TextInput/TextInput.tsx
Required change for this [ClickUp ticket](https://app.clickup.com/t/z3yx18)
> feat: Add autocomplete property for TextInput

- package-lock.json
- package.json
Upgrade cypress to be ready for Tailwind 3
Solved Issue:
- https://tagmerge.com/issue/cypress-io/cypress/19727
- https://github.com/cypress-io/cypress/pull/19676/files
> fix: Upgrade to Cypress 9.3.1

- src/components/RichTextEditor/RichTextEditor.tsx
- src/components/RichTextEditor/hooks/useEditorSelection.ts
concerns this ticket: https://app.clickup.com/t/1vqjqh3
Position of the toolbar should now also work when scrolling
> fix: RichTextEditor toolbar position when scrolling

- src/components/RichTextEditor/BlockStyleButton.tsx
- src/components/RichTextEditor/RichTextEditor.spec.tsx
- src/components/RichTextEditor/RichTextEditor.stories.tsx
- src/components/RichTextEditor/RichTextEditor.tsx
- src/components/RichTextEditor/Toolbar.tsx
- src/components/RichTextEditor/renderer/renderBlockStyles.tsx
- src/components/RichTextEditor/state/toolbar/actions.ts
- src/components/RichTextEditor/state/toolbar/machine.ts
This PR implements the text alignment controls in the rich text editor.
Clickup-ticket: https://app.clickup.com/t/1rp6wxd
> feat(rich-text-editor): add text alignment controls

- src/components/Slider/Slider.tsx
Fixes the animation on a Slider when inside a Flyout, thanks to @SamCreasey for the hint to the solution. :)
> fix(slider): strange animation behaviour

- src/foundation/layout/Stack/Stack.spec.tsx
- src/foundation/layout/Stack/Stack.stories.tsx
- src/foundation/layout/Stack/Stack.tsx
BREAKING CHANGE: New Spacing and Padding Prop Values
> fix(Stack): Use New Spacing Tokens

- src/components/Accordion/Accordion.spec.tsx
- src/components/Accordion/Accordion.stories.tsx
- src/components/Accordion/Accordion.tsx
This PR allows for Accordion sections being open by default when the active header property is set to true.
https://app.clickup.com/t/1y7qr5d
> feat(Accordion): allow sections to be open by default (fixed)

- src/layout/Stack/Stack.spec.tsx
- src/layout/Stack/Stack.stories.tsx
- src/layout/Stack/Stack.tsx
- vite.config.ts
This adds two new properties to the stack component for aligning and justifying content within the stack using tailwind classes. It also updates the vite.config to export the stack and typography components.
> feat(stack): align and justify

- src/components/Badge/Badge.spec.tsx
- src/components/Badge/Badge.stories.tsx
- src/components/Badge/Badge.tsx
Ticket: https://app.clickup.com/t/256tm5y
- Added disabled, emphasis and size properties
- added new styles for emphasis and disabled states,
- modified existing style classes to match new arcade tokens
- added new tests for new props
- updated storybook with new properties
> feat(badge): next badge styles

- src/components/Card/Card.spec.tsx
- src/components/Card/Card.stories.tsx
- src/components/Card/Card.tsx
Added an onClick handler to the card component, and added button/focus styles for accessibility when the onClick prop is supplied. 
Updated tests to cover new prop
> feat(card): added onClick handler

- src/components/Badge/Badge.spec.tsx
- src/components/Badge/Badge.stories.tsx
- src/components/Badge/Badge.tsx
Modify the new badge component so that it accepts the Color object as a status type
> feat(badge): add new status type

- src/components/Accordion/Accordion.spec.tsx
- src/components/Badge/Badge.spec.tsx
- src/components/Button/Button.spec.tsx
- src/components/Checkbox/Checkbox.spec.tsx
- src/components/Checklist/Checklist.spec.tsx
- src/components/ColorInputFlyout/ColorPickerFlyout.spec.tsx
- src/components/ColorPicker/ColorPicker.spec.tsx
- src/components/Dropdown/Dropdown.spec.tsx
- src/components/FieldsetHeader/FieldsetHeader.spec.tsx
- src/components/Flyout/Flyout.spec.tsx
- src/components/MenuItem/MenuItem.spec.tsx
- src/components/MultiSelect/MultiSelect.spec.tsx
- src/components/Slider/Slider.spec.tsx
- src/components/Table/Table.spec.tsx
- src/components/Tag/Tag.spec.tsx
- src/components/TextInput/TextInput.spec.tsx
Prevent duplicated tests by removing imports/exports from spec files in arcade
> fix(testing): prevent duplicated tests

- src/components/Tabs/TabItem.tsx
- src/components/Tabs/Tabs.spec.tsx
- src/components/Tabs/Tabs.stories.tsx
- src/components/Tabs/Tabs.tsx
- src/components/Tabs/index.ts
> feat: Create Tabs Component

- src/components/LinkChooser/LinkChooser.spec.tsx
- src/components/LinkChooser/mock/data.ts
- src/components/LinkChooser/mock/guidelines.ts
- src/components/LinkChooser/mock/templates.ts
- src/components/LinkChooser/types.ts
In the scope of this ticket: https://app.clickup.com/t/2322dnk
> refactor: remove ExtraSection items prop in LinkChooser

- src/components/TextInput/TextInput.stories.tsx
- src/components/TextInput/TextInput.tsx
> feat(textInput): Add control to enable or disable spellcheck

- src/components/AssetInput/AssetInput.stories.tsx
- src/components/AssetInput/AssetInput.tsx
- src/components/AssetInput/SpinningCircle.tsx
Concerns this ticket: https://app.clickup.com/t/23ypf0v
Adds a loading prop and animation for the AssetInput
> feat: add AssetInput loading animation

- src/components/DatePicker/index.ts
- src/components/index.ts
How to test: 
Run `npm build`, `dist/src/components/datepicker/`should now be available
> fix(datepicker): Add datepicker to the bundle

- src/components/ColorInputFlyout/ColorPickerFlyout.spec.tsx
- src/components/ColorInputFlyout/ColorPickerFlyout.stories.tsx
- src/components/ColorInputFlyout/ColorPickerFlyout.tsx
- src/components/ColorInputFlyout/ColorPickerTrigger.tsx
required for https://app.clickup.com/t/26ewqfn
> feat(ColorInputTrigger): Add clear button

- src/components/Accordion/Accordion.tsx
- src/components/FieldsetHeader/FieldsetHeader.tsx
[ticket](https://app.clickup.com/t/2326ucr)
> fix: font weight accordion header in fieldsetHeader

- src/components/Dropdown/Dropdown.spec.tsx
- src/components/Dropdown/Dropdown.stories.tsx
- src/components/Dropdown/Dropdown.tsx
Adding alignment Left, Middle, Right.
+ Fixing Animation glitch
> feat(dropdown): Add Alignment options

- src/components/LinkChooser/utils/helpers.ts
- src/components/LinkChooser/utils/transformers.ts
Resolves issue `Adding a custom URL leads the user to a 404 Page`
Ticket: https://app.clickup.com/t/2a1aa72
> fix(LinkChooser): add missing https to custom link

- src/components/LinkChooser/LinkChooser.tsx
- src/components/LinkChooser/SearchInput.tsx
This PR fixes the following issues:
- Selected link disappears, after you open the settings again an select the input (see Schirmis Loom)
- Typing after selecting a link does not work.
Ticket: https://app.clickup.com/t/2a1aa72
> fix(LinkChooser): input value

- src/components/ColorPicker/ColorPicker.css
- src/components/ColorPicker/ColorPicker.tsx
Adds correct focus style for custom color picker.
Ticket: https://app.clickup.com/t/2201b2q
> feat(ColorPicker): add accessibility focus style

- src/components/LinkChooser/LinkChooser.tsx
- src/components/LinkChooser/NavigationMenu.tsx
- src/components/LinkChooser/SearchResultOption.tsx
- src/components/LinkChooser/SearchResultSection.tsx
- src/components/LinkChooser/state/actions.ts
- src/components/LinkChooser/state/machine.ts
- src/components/LinkChooser/state/types.ts
- src/components/LinkChooser/utils/state.ts
`import {...} from ".";` make a cyclic dependency as it does `index.ts -> foo.ts -> index.ts -> bar.ts`
> fix: remove circular dependencies

- src/components/MenuItem/MenuItem.stories.tsx
> docs(menuItem): Remove onclick from story

- src/components/Badge/Badge.spec.tsx
- src/components/Badge/Badge.stories.tsx
- src/components/Badge/Badge.tsx
- src/components/Badge/helpers.ts
- src/components/Badge/index.ts
- src/components/Badge/types.ts
- src/components/Breadcrumbs/Breadcrumbs.stories.tsx
- src/components/Breadcrumbs/Breadcrumbs.tsx
- src/components/Breadcrumbs/CurrentBreadcrumbItem.tsx
- src/components/Flyout/Flyout.stories.tsx
- src/components/Flyout/Flyout.tsx
Convert the badge "emphasis" prop to accept a BadgeEmphasis enum and also create new files for existing functions/types in the Badge folder to tidy up Badge.tsx
> fix(badge)!: convert badge emphasis property to enum

- src/components/LinkChooser/SearchResultsList.tsx
Resolve issues with LinkChooser functionality: https://app.clickup.com/t/2a1aa72
> fix(LinkChooser): adjust empty results container height

- src/components/Accordion/Accordion.stories.tsx
- src/components/LinkChooser/LinkChooser.tsx
Fix issue where LinkChooser dropdown is hidden inside an accordion item.
Ticket: https://app.clickup.com/t/289q0kv
> fix(LinkChooser): overflow issue inside Accordion

- src/components/AssetInput/SingleAsset/SelectedAsset.tsx
- src/components/LinkChooser/LinkChooser.tsx
Adjust width of flyout on resize in LinkChooser & AssetChooser.
> fix(LinkChooser & AssetChooser): adjust width on resize

- src/components/LinkChooser/LinkChooser.tsx
Fixes https://frontify.slack.com/archives/C031PENPQE6/p1650983053288949
> style: higher zIndex dropdown link chooser

- src/components/TextInput/TextInput.spec.tsx
- src/components/TextInput/TextInput.tsx
Same issue as here: https://github.com/Frontify/arcade/pull/731
Just a quick fix that shouldn't affect any existing use cases.
> fix(TextInput): adjust button types

- src/components/Tabs/Tabs.tsx
Fixes uncontrollable form submission when tab buttons are clicked
> fix: add button type to tab

- .husky/pre-push
- package-lock.json
- package.json
Remove pre-push hook as the tests are taking just too long
> chore: remove husky

- src/components/Badge/helpers.ts
@imoutaharik teeeeeny weeeeeny review please
Related to #763
> fix(badge): hover style

- src/components/Badge/Badge.tsx
- src/components/Breadcrumbs/BreadcrumbItem.tsx
- src/components/Breadcrumbs/CurrentBreadcrumbItem.tsx
- src/components/ColorInputFlyout/ColorPickerTrigger.tsx
- src/components/ColorPicker/BrandColorPicker.tsx
- src/components/LinkChooser/SearchInput.tsx
- src/components/RadioPill/RadioPill.tsx
- src/components/RichTextEditor/TextStyleDropdown/DropdownItem.tsx
- src/components/RichTextEditor/TextStyleDropdown/DropdownTrigger.tsx
- src/components/TextInput/TextInput.tsx
- src/components/TooltipIcon/TooltipIcon.tsx
- src/components/Trigger/Trigger.tsx
Added button types to prevent form submission when interacting with elements in Clarify.
> fix(button): add button types to components

- src/components/Modal/Modal.tsx
- src/components/Modal/types.ts
This adds a `zIndex` prop for the Modal
> feat: add zIndex prop to the Modal

- src/components/Tree/Node.tsx
- src/components/Tree/Tree.spec.tsx
- src/components/Tree/Tree.tsx
- src/components/Tree/components/EditableNodeItem.tsx
- src/components/Tree/utils/mocks.tsx
This was discussed in this [Slack thread](https://frontify.slack.com/archives/C02PSJTPA3D/p1650997178045199?thread_ts=1650372981.299969&cid=C02PSJTPA3D).
@julianiff
The PR is not complete (test failing, logs, etc.), just want to sync with you first on the implementation, fix any big issues if any, and then complete everything so we skip double work.
> feat(Tree): create editable Tree node item

- src/components/LinkChooser/utils/helpers.ts
To fix https://frontify.slack.com/archives/C031PENPQE6/p1652368375709749
> fix: allow `mailto` and `tel` links

- src/components/FormControl/FormControl.tsx
[Ticket](https://app.clickup.com/t/2bgv718)
> fix(AssetInput): overflow in icon asset block

- README.md
- package-lock.json
- package.json
- src/styles.css
- src/tokens/Colors.stories.tsx
- tailwind.config.js
Please do a smoke test since this PR changes from arcade-tokens to fondue-token.s
> chore(fondue-tokens): renaming - replace arcade-tokens with fondue-tokens

- src/components/RichTextEditor/RichTextEditor.spec.tsx
- src/components/RichTextEditor/components/chosen-link.tsx
- src/components/RichTextEditor/plugins/linkChooserPlugin/createLinkChooserPlugin.ts
- src/components/RichTextEditor/plugins/linkChooserPlugin/transforms/getAndUpsertLink.ts
- src/components/RichTextEditor/plugins/linkChooserPlugin/transforms/upsertLinkAtSelection.ts
- src/components/RichTextEditor/plugins/linkChooserPlugin/transforms/wrapLink.ts
- src/components/RichTextEditor/plugins/linkChooserPlugin/types.ts
- src/components/RichTextEditor/plugins/linkChooserPlugin/ui/EditLinkChooserButton.tsx
- src/components/RichTextEditor/plugins/linkChooserPlugin/ui/LinkChooserFlyout.tsx
- src/components/RichTextEditor/plugins/linkChooserPlugin/ui/LinkChooserPreviewFlyout.tsx
- src/components/TextInput/TextInput.tsx
https://app.clickup.com/t/1r58b4m
> feat(RichText): improving UX for linkchooser in rte

- src/components/Accordion/Accordion.spec.tsx
Forgot to add a test-case to avoid regressions.
> chore: add test for open accordionItem functionality

- src/components/RichTextEditor/RichTextEditor.spec.tsx
Clickup-ticket: https://app.clickup.com/t/2fzy9ed
> feat(RichTextEditor): add tests for legacy link format

- pnpm-lock.yaml
- src/components/RichTextEditor/DesignTokensContext.ts
- src/components/RichTextEditor/RichTextEditor.spec.tsx
- src/components/RichTextEditor/RichTextEditor.tsx
- src/components/RichTextEditor/TextStyleDropdown/TextStyleDropdown.tsx
- src/components/RichTextEditor/components/Toolbar/ButtonGroup.tsx
- src/components/RichTextEditor/components/Toolbar/Toolbar.tsx
- src/components/RichTextEditor/components/custom1.tsx
- src/components/RichTextEditor/components/custom2.tsx
- src/components/RichTextEditor/components/custom3.tsx
- src/components/RichTextEditor/components/heading1.tsx
- src/components/RichTextEditor/components/heading2.tsx
- src/components/RichTextEditor/components/heading3.tsx
- src/components/RichTextEditor/components/heading4.tsx
- src/components/RichTextEditor/context/DesignTokensContext.ts
- src/components/RichTextEditor/types.ts
- src/components/RichTextEditor/utils/editorConfig.ts
https://app.clickup.com/t/2cdd1dd
> feat(RichTextEditor): add design tokens to context api

- src/components/AssetInput/AssetInput.stories.tsx
- src/components/AssetInput/SingleAsset/AssetSubline.tsx
Ticket: https://app.clickup.com/t/29add14
> fix(AssetInputBlock): spacing issue

- src/components/Tabs/Tabs.tsx
Fix for issue when switching between different tab components causing an animation glitch due to sharing a group id.
https://user-images.githubusercontent.com/93908356/179199193-5c6a0316-bd24-49b8-a88a-e1ef70468175.mov
To replicate the issue replace Tabs storybook with this code:
```
const TabWithBadgeTemplate: Story<TabsProps> = (args) => {
const [activeItemId, setActiveItemId] = useState(data[0].id);
const [toggle, setToggle] = useState(false);
return (
<div>
{toggle ? (
<>
<div className="tw-h-[100px] tw-w-full"></div>
<Tabs {...args} activeItemId={activeItemId} onChange={(value) => setActiveItemId(value)}>
{dataWithBadge.map((item) => (
<TabItem
id={item.id}
key={item.id}
label={item.label}
disabled={item.disabled ?? false}
badge={item.badge}
>
<div …
```
> fix(Tabs): isolate tab id

- package.json
- tsconfig.json
- vite.config.ts
Can be merged as soon as https://github.com/Frontify/frontify-cli/pull/226 got released
> chore: Use preserveModules for esm build

- src/components/Table/Table.tsx
- src/components/Table/TableHeaderRow.tsx
Table header now sticks to the top of the container
> feat(table): add sticky header

- package-lock.json
- package.json
Cypress tests were failing with external issues, this upgrade fixes it.
> chore(cypress): upgrade to 10.7.0

- src/components/EditableInput/EditableInput.cy.tsx
- src/components/EditableInput/EditableInput.stories.tsx
- src/components/EditableInput/EditableInput.tsx
- src/components/EditableInput/index.ts
- src/components/Tree/Node.tsx
- src/components/Tree/Tree.cy.tsx
- src/components/index.ts
New Component EditableNode moved from Tree to own component
> feat(EditableInput): Move EditableInput into own component

- src/components/Switch/Switch.tsx
Make use of correct design tokens for switch.
- https://www.figma.com/file/pevuvey1joCsopTRr9f4OE/Fondue---Components?node-id=11931%3A550233
- https://app.clickup.com/t/2xq1yvk
> fix(Switch): refactor to use design tokens

- src/components/Badge/Badge.cy.tsx
- src/components/Badge/Badge.stories.tsx
- src/components/Badge/Badge.tsx
- src/components/Badge/BadgeStatusIcon.tsx
- src/components/Badge/helpers.ts
- src/components/Badge/types.ts
Updated the badge spacing to match the design in Figma https://www.figma.com/file/pevuvey1joCsopTRr9f4OE/Fondue---Components?node-id=13856%3A256660 . This includes a single edge case where spacing is slightly narrower if all 3 components exist on a larger badge.
> fix(badge)!: update spacing

- .storybook/frontifyTheme.ts
- .storybook/preview-head.html
- .storybook/preview.tsx
- src/styles.css
Is neede dby the Button PR to introduce the possibility to use the Dark theme. (Updated the old PR to be up-to-date with the main branch.
> feat(theme-switcher): Add control to see side-by-side of components [Button #1]

- src/components/RichTextEditor/RichTextEditor.tsx
- src/components/RichTextEditor/helper.ts
https://app.clickup.com/t/2xd3m8g
> feat(RichTextEditor): blur RTE on tab

- src/components/EditableText/EditableText.stories.tsx
- src/components/EditableText/EditableText.tsx
- src/components/EditableText/lib/helper.ts
- src/components/Tree/Node.tsx
- Remove padding from story
- Add fontWeight new to style extracting
- Add Padding to editableText and add flag to remove it if needed
> fix(EditableText): Add new padding property and fix classes not applying properly

- src/components/Button/Button.tsx
Reverts Frontify/fondue#980
- Add useFocusRing to fix focusRing issue
> fix(Button): revert remove button react-aria and add FocusRing

- src/components/AssetInput/AssetInput.tsx
Fix styling issue in asset input block. Both buttons should have the same color and font-weight
> fix(asset-input): Different button styles

- src/components/Badge/helpers.ts
Correct text color classname that was not being applied correctly
> fix(badge): correct color classname

- .eslintrc.js
- src/components/Accordion/Accordion.tsx
- src/components/ActionMenu/Aria/AriaMenuItem.tsx
- src/components/Checklist/Checklist.tsx
- src/components/ColorPicker/BrandColorPicker.tsx
- src/components/ColorPicker/CustomColorPicker.tsx
- src/components/DropZone/DropZone.cy.tsx
- src/components/Dropdown/Dropdown.tsx
- src/components/Dropdown/useDropdownAutoHeight.ts
- src/components/LinkChooser/LinkChooser.tsx
- src/components/LinkChooser/NavigationMenu.tsx
- src/components/LinkChooser/SearchResultsList.tsx
- src/components/ScrollWrapper/hooks/useScrollWrapper.ts
- src/components/Slider/Slider.tsx
- src/components/Tabs/Tabs.stories.tsx
- src/components/Tabs/Tabs.tsx
- src/components/Tooltip/Tooltip.tsx
- src/foundation/Icon/Icon.stories.tsx
- src/hooks/useClickOutside.ts
1. Enable Rules of Hooks in eslint config.
2. Fix all rules of hooks errors
3. Fix all rules of hooks warnings (exhaustive-deps)
> fix(lint): Enable rules of hooks

- src/components/RichTextEditor/Plugins/GeneratePlugins.tsx
- src/components/RichTextEditor/RichTextEditor.tsx
Had to move the hook inside of the method thats why is Capitalized and also other methods that it is the same.
> fix(Rich Text Editor): improved plugin generator - the hook should be executed inside plate

- src/components/LoadingBar/LoadingBar.cy.tsx
- src/components/LoadingBar/LoadingBar.stories.tsx
- src/components/LoadingBar/LoadingBar.tsx
- src/components/LoadingBar/index.ts
Added the [Loading bar](https://www.figma.com/file/pevuvey1joCsopTRr9f4OE/Fondue---Components?node-id=12398%3A207074) component .
The component does not emit the events described in the Figma component as we decided it was no longer necessary
> Feat: loading bar

- src/components/index.ts
Forgot to export the component 🙃
> fix: export loading bar

- src/components/OverflowMenu/OverflowMenu.cy.tsx
- src/components/OverflowMenu/OverflowMenu.stories.tsx
- src/components/OverflowMenu/OverflowMenu.tsx
- src/components/OverflowMenu/index.ts
- src/components/index.ts
This PR also introduces:
- export `OverflowMenu` component
> refactor(OverflowMenu): remove custom trigger from OverflowMenu

- src/components/DatePicker/DatePickerTrigger.tsx
Trigger Accessibility:
It's now accessible by pressing Enter key. It now opens the datepicker.
> fix(Datepicker): Trigger accessibility and caret position issue

- src/components/ColorPicker/ColorPreview.tsx
- src/components/Flyout/FlyoutFooter.tsx
- src/components/Flyout/Overlay.tsx
> Revert "fix(Flyout): missing outline and rounded corners"

- src/components/Dropdown/Dropdown.stories.tsx
- src/components/Dropdown/Dropdown.tsx
- src/components/Trigger/Trigger.tsx
This PR adds the `emphasis` prop to the `Dropdown` component, as we need it for the new Code Snippet block.
> feat(Dropdown): add emphasis

- src/components/Dropdown/Dropdown.stories.tsx
- src/components/Dropdown/Dropdown.tsx
- src/components/Menu/Menu.cy.tsx
- src/components/Menu/Menu.tsx
- src/components/Menu/useMenuKeyboardNavigation.ts
- src/components/MenuItem/MenuItem.tsx
- src/components/MultiSelect/MultiSelect.stories.tsx
- src/components/MultiSelect/MultiSelect.tsx
- src/components/MultiSelect/SelectMenuItems/SelectMenuItems.tsx
- src/components/MultiSelect/SelectMenuItems/index.ts
- src/components/MultiSelect/helpers.ts
- src/components/Trigger/Trigger.tsx
New variant for asset audit trail in `MultiSelect` component. This component should still work retroactively
> feat(multiselect): add multiSelect weak emphasis

- tailwind.config.js
Add explicit breakpoints to be used
> chore: add explicit breakpoints

- src/components/RichTextEditor/Plugins/EmojiPlugin/index.ts
- src/components/RichTextEditor/Plugins/GeneratePlugins.tsx
- src/components/RichTextEditor/Plugins/Plugin.ts
- src/components/RichTextEditor/Plugins/PluginComposer.ts
- src/components/RichTextEditor/Plugins/types.ts
- src/components/RichTextEditor/RichTextEditor.cy.tsx
- src/components/RichTextEditor/RichTextEditor.stories.tsx
- src/components/RichTextEditor/RichTextEditor.tsx
- src/components/RichTextEditor/Toolbar/ToolbarPositionWithButtons.ts
- src/components/RichTextEditor/Toolbar/index.tsx
- src/components/RichTextEditor/Toolbar/types.ts
- src/components/RichTextEditor/helpers/forceToBlurActiveElement.ts
- src/components/RichTextEditor/helpers/index.ts
- src/components/RichTextEditor/index.ts
- src/components/RichTextEditor/serializer/index.ts
Refactored Toolbar buttons to be independent of position.
Exposed Serializer.
Added additional prop 'onKeyDown' to Rich Text Editor
> feat(Rich Text Editor): improve toolbar plugin composer

- package-lock.json
- package.json
> chore(Rich Text Editor): plate update 18.14.3

- package-lock.json
- package.json
> chore: update fondue-tokens

- src/components/RichTextEditor/serializer/markdown/__tests__/MarkdownToSlate.spec.ts
- src/components/RichTextEditor/serializer/markdown/__tests__/SlateToMarkdown.spec.ts
- src/components/RichTextEditor/serializer/markdown/__tests__/fixtures/mentions.ts
- src/components/RichTextEditor/serializer/markdown/__tests__/fixtures/mixed.ts
- src/components/RichTextEditor/serializer/markdown/deserializer/deserialize.ts
- src/components/RichTextEditor/serializer/markdown/remarkMention/index.ts
- src/components/RichTextEditor/serializer/markdown/serializer/applyFormattingToBlockNode.ts
- src/components/RichTextEditor/serializer/markdown/serializer/serialize.ts
Improved Serializer for transforming mentions
> fix(Rich Text Editor): markdown serializer and deserializer

- src/components/MultiSelect/MultiSelect.stories.tsx
- src/components/MultiSelect/MultiSelect.tsx
- src/components/MultiSelect/SelectMenuItems/SelectMenuItems.tsx
> chore(multiselect): add prop to pass custom avatar components to menu item

- src/components/MultiSelect/MultiSelect.tsx
Beside fixing the weak emphasis MultiSelect type, this PR also fixes this issue: https://app.clickup.com/t/2523021/TASK-6028
> fix(MultiSelect): Weak emphasis fixes

- src/components/Checkbox/Checkbox.cy.tsx
- src/components/Checkbox/Checkbox.stories.tsx
- src/components/Checkbox/Checkbox.tsx
> fix: Revert "fix(Checkbox)!: adding emphasis styles, moving notes to below label"

- src/components/Checkbox/Checkbox.cy.tsx
- src/components/Checkbox/Checkbox.stories.tsx
- src/components/Checkbox/Checkbox.tsx
- src/components/Checklist/Checklist.tsx
- src/components/MultiSelect/MultiSelect.cy.tsx
- src/components/RichTextEditor/RichTextEditor.cy.tsx
- src/components/Table/TableCell.tsx
- src/components/Table/TableColumnHeader.tsx
- src/components/TooltipIcon/TooltipIcon.stories.tsx
- src/components/TooltipIcon/TooltipIcon.tsx
> fix: Revert "fix(Checkbox): fixing accessibility errors"

- src/components/Tree/TreeItem.tsx
- src/components/Tree/utils/index.ts
- src/components/Tree/utils/isInsideOfElement.ts
Prevent this issue when clicking the tooltip
https://user-images.githubusercontent.com/6846950/217806712-8a522450-09b5-4c7e-8647-4c1772a690b9.mov
> fix: prevent selection click when clicking contentComponent

- src/components/DatePicker/DatePicker.css
- src/components/DatePicker/DatePicker.cy.tsx
- src/components/DatePicker/DatePicker.stories.tsx
- src/components/DatePicker/DatePicker.tsx
- src/components/DatePicker/DatePickerTrigger.tsx
Some new props were exposed to accomplish this, please refer to the `DatePicker` type changes
> feat(date picker): add range variant for date picker

- src/components/RichTextEditor/Plugins/InitPlugin/id.ts
- src/components/RichTextEditor/Plugins/InitPlugin/index.ts
- src/components/RichTextEditor/Plugins/index.ts
- src/components/RichTextEditor/RichTextEditor.stories.tsx
- src/components/RichTextEditor/__tests__/RichTextEditor.cy.tsx
This reverts commit 67790d9acd7b5d3f357ce34351a753d8f4118e66.
> fix(Rich Text Editor): revert removed rte init plugin (#1247)

- src/components/RichTextEditor/serializer/utils/serializeNodeToHtmlRecursive.ts
Missing quotation mark in the `paragraph`
> fix(RTE): add missing quotation mark in serializer

- src/components/RichTextEditor/serializer/nodes/link.ts
- src/components/RichTextEditor/serializer/utils/serializeNodeToHtmlRecursive.spec.ts
Regards this ticket: https://app.clickup.com/t/8677k32g3
> fix(RTE): Html serializer ignoring link target

- src/components/Tree/TreeItem.tsx
Selected styles have been replaced with 'neutral strong' styles in the figma design
> feat: modify selected styles for tree

- src/components/DatePicker/DatePicker.css
- src/components/DatePicker/DatePicker.stories.tsx
- src/components/DatePicker/DatePicker.tsx
Add prevent open on focus optional prop and onKeyDown callback to control open/close with ref
> chore(datepicker): QoL improvements 

- src/components/RichTextEditor/Plugins/CheckboxListPlugin/CheckboxListButton/CheckboxListToolbarButton.tsx
- src/components/RichTextEditor/Plugins/CheckboxListPlugin/CheckboxListElement.tsx
- src/components/RichTextEditor/Plugins/TextStylePlugin/TextStyleDropdown/DropdownItem.tsx
- src/components/RichTextEditor/Plugins/TextStylePlugin/TextStyleDropdown/useSelectedTextStyles.ts
- src/components/RichTextEditor/__tests__/RichTextEditor.cy.tsx
ticket: https://app.clickup.com/t/8677k2m9m
> feat(RichTextEditor): render checklists with textstyles

- src/components/Tree/TreeItem.tsx
It's now 20x20px [as per Simone's request](https://app.clickup.com/t/8677f18fd?comment=90100009095074&threadedComment=90030012397011).
> fix(TreeItem): Increase caret clickable area

- src/components/RichTextEditor/Plugins/CheckboxListPlugin/CheckboxListButton/CheckboxListToolbarButton.tsx
- src/components/RichTextEditor/Plugins/TextStylePlugin/TextStyleDropdown/DropdownItem.tsx
- src/components/RichTextEditor/helpers/exampleValues/exampleValues.ts
ticket: https://app.clickup.com/t/8677k2m9m
> feat(RTE): keep textstyles by switching to lists

- src/components/TextInput/TextInput.cy.tsx
- src/components/TextInput/TextInput.stories.tsx
- src/components/TextInput/TextInput.tsx
This adds the custom `extraAction` icon button to the `TextInput`
> feat: Add TextInput extraAction

- src/components/Tree/TreeItem/ExpandButton.tsx
Make invisible carets on tree when they are disable
https://app.clickup.com/t/862jp8qj0
> feat: hide disable carets on tree

- src/components/RichTextEditor/EditorPositioningWrapper/ToolbarWrapper/ToolbarWrapperPositioningFloating.tsx
- src/components/RichTextEditor/EditorPositioningWrapper/ToolbarWrapper/types.ts
- src/components/RichTextEditor/Plugins/GeneratePlugins.tsx
- src/components/RichTextEditor/RichTextEditor.stories.tsx
- src/components/RichTextEditor/RichTextEditor.tsx
- src/components/RichTextEditor/Toolbar/index.tsx
- src/components/RichTextEditor/Toolbar/types.ts
Added a prop to control the width of the toolbar better
[Task](https://app.clickup.com/t/8677uxbye)
> feat(RichTextEditor): ToolbarWidth

- package.json
- pnpm-lock.yaml
- src/components/Tree/Tree.cy.tsx
- src/components/Tree/Tree.stories.tsx
- src/components/Tree/Tree.tsx
- src/components/Tree/TreeContext.ts
- src/components/Tree/TreeItem/TreeItem.tsx
- src/components/Tree/types.ts
- src/components/Tree/utils/index.ts
- src/components/Tree/utils/useDeepCompareEffect.spec.cy.tsx
- src/components/Tree/utils/useDeepCompareEffect.ts
- tsconfig.json
- Fixed infinite loop when opening items
- Added `showCaret` prop to `TreeItem`
- Added `onShrink` prop to `Tree`
- Remove `FC` type in `contentComponent`
> fix: infinite loop when opening items

- src/components/RichTextEditor/Plugins/MentionPlugin/helpers/mapMentionable.ts
- src/components/RichTextEditor/serializer/serializeToHtml.spec.ts
- src/components/RichTextEditor/serializer/serializeToHtml.ts
Added test because the method was failing and it was failing because of incorrectly imported types.
> fix(Rich Text Editor): updated type export

- src/components/Tree/TreeItem/TreeItem.tsx
Accessibility improvement: Cursor changes when an TreeItem can or cannot be dropped in tree
> feat(Tree): cursor change can/cannot drop item

- src/components/RichTextEditor/serializer/utils/serializeLeafToHtml.spec.ts
- src/components/RichTextEditor/serializer/utils/serializeLeafToHtml.ts
Ticket: https://app.clickup.com/t/86780479v
> fix(RTE): add sub- and superscript to serializer

- src/components/RichTextEditor/Plugins/ListPlugin/index.ts
- src/components/RichTextEditor/Plugins/helper.tsx
- src/components/RichTextEditor/serializer/nodes/default.ts
- src/components/RichTextEditor/serializer/utils/serializeNodeToHtmlRecursive.spec.ts
Reverts changes done in #1446  and partly in #1443
> fix(RTE): revert serializer

- src/components/Tree/helpers/projection.ts
> fix(Tree): DnD direction positioning correction

- src/components/Tree/Tree.stories.tsx
- src/components/Tree/Tree.tsx
- src/components/Tree/TreeItem/TreeItem.tsx
- src/components/Tree/helpers/reducer.spec.cy.tsx
- src/components/Tree/helpers/reducer.ts
- src/components/Tree/utils/mocks.ts
Some cleaning and optimization of the Tree component code.
Optimization on how the reducer catches node changes for node with no `contentComponent` props, like some wrappers. This ensures re-render when needed.
> fix: Tree bugs and optimization

- src/components/Tree/Tree.tsx
- src/components/Tree/TreeItem/TreeItem.tsx
- src/components/Tree/TreeItem/useTreeItem.ts
- src/components/Tree/helpers/constants.ts
- src/components/Tree/helpers/reducer.spec.cy.tsx
- src/components/Tree/helpers/reducer.ts
Fixes extra re-renderings, adds logic to expand on hover, and optimizes some logic
> fix: tree component improvements

- src/components/Tree/Tree.cy.tsx
- src/components/Tree/TreeItem/DragHandle.tsx
- src/components/Tree/TreeItem/TreeItemOverlay.tsx
- src/components/Tree/utils/mocks.ts
replaces https://github.com/Frontify/fondue/pull/1408
> feat: Tree tests

- package.json
- pnpm-lock.yaml
> chore: latest plate

- src/components/Tree/Tree.tsx
- src/components/Tree/TreeItem/TreeItem.tsx
- src/components/Tree/helpers/nodes.ts
- src/components/Tree/helpers/reducer.ts
- src/components/Tree/types.ts
Fixes some inconsistencies and prevents some infinite loops.
Also we try to keep any current children when updating parent nodes if the parent is expanded, so we don't have weird flickerings.
> feat: tree optimization

- src/components/Tree/TreeItem/TreeItem.tsx
smooth color transitions on treeItem
> refactor: (Tree) smooth ui effects

- src/components/Tree/Tree.cy.tsx
- src/components/Tree/helpers/nodes.spec.cy.tsx
- src/components/Tree/helpers/reducer.spec.cy.tsx
some updates for Tree component and helpers tests
> test: (Tree) add and update component and helper tests

- src/components/InlineDialog/InlineDialog.cy.tsx
- src/components/Trigger/Trigger.tsx
This makes the caret on the Dropdown and MultiSelect not focusable.
> fix(Trigger): Caret not focusable on Dropdown and MultiSelect.

- src/components/DatePicker/DatePicker.stories.tsx
- src/components/DatePicker/DatePicker.tsx
> chore(datepicker): add custom header prop to datepicker

- src/components/RichTextEditor/EditorPositioningWrapper/ToolbarWrapper/ToolbarWrapperPositioningFloating.tsx
[Task](https://app.clickup.com/t/8677hxu55)
> fix(RTE): deactivate floating toolbar animation

- src/components/Tree/TreeItem/TreeItem.tsx
- src/components/Tree/helpers/projection.ts
more strict checks for max and min allowed depth for each element.
cc: @imoutaharik
> fix(Tree): misleading feedback and indentation

- src/components/ColorInputFlyout/ColorPickerTrigger.tsx
- src/components/Dropdown/Dropdown.tsx
- src/components/Trigger/Trigger.tsx
> fix: dropdown caret positioning

- .github/semantic.yml
- .github/workflows/continuous-deployment.yml
- .github/workflows/continuous-integration.yml
- .github/workflows/pull-request-title.yml
- .github/workflows/pull-request.yml
- .releaserc
- renovate.json
Also:
- Cleaned the prefixes for pr title validation
- Removed automerge on renovate
> ci: fix deprecation notice

- src/components/RichTextEditor/Plugins/CodePlugin/CodeMarkupElement.tsx
- src/components/RichTextEditor/__tests__/RichTextEditor.cy.tsx
- src/components/RichTextEditor/__tests__/TextStylePlugin.cy.tsx
Adjust the color as it's wanted within [Desgin](https://www.figma.com/file/pYt8ECuB6Sc63cVtpKiDgf/Blocks---Updated?type=design&node-id=1533-355029&mode=design&t=x46R8LYGuOJrecWX-0)
> fix(RTE): CodePlugin fix color 

- src/components/OrderableList/types.ts
- src/components/Tree/Tree.tsx
- src/components/Tree/TreeItem/TreeItemOverlay.tsx
- src/components/Tree/helpers/getMovementAnnouncements.ts
- src/components/Tree/helpers/index.ts
- src/components/Tree/helpers/nodes.ts
- src/components/Tree/helpers/reducer.ts
- src/components/Tree/helpers/sensorsActivationConstraint.tsx
- src/components/Tree/helpers/treeHandleKeyDown.tsx
- src/components/Tree/types.ts
reducing complexity for SonarCloud (was 91, it should be < 15)
> refactor: reduce Tree complexity

- src/components/RichTextEditor/Plugins/CheckboxListPlugin/CheckboxListElement.tsx
[Task](https://app.clickup.com/t/8692pwtcj)
Basically it just centers the checkbox right to the text.
> fix(RTE): checkbox plugin positioning

- src/components/TextInput/TextInput.tsx
- src/components/Textarea/Textarea.tsx
Update hover state styling on `TextInput` and `Textarea` components to `line-x-strong`
> chore: update hover state on inputs to new style

- src/components/Dialog/Dialog.stories.tsx
- src/components/Dialog/Dialog.tsx
- src/components/InlineDialog/InlineDialog.stories.tsx
- src/components/InlineDialog/InlineDialog.tsx
- src/components/Popper/Popper.stories.tsx
- src/components/Popper/Popper.tsx
- src/components/Popper/types.ts
- src/utilities/dialogs/Overlay.tsx
The loom shows scrolling when modal is not open and blocked scroll when modal is open. You cant see by i try to scroll when modal is open but it does not move :)
https://www.loom.com/share/fd863df2fa93459fa26a83886bff01e5
This video shows the behaviour before this changes
https://www.loom.com/share/bcad8fe83a8a4fe88b569b8bb0ccbd38
> fix: block scrolling on modal

- package.json
- pnpm-lock.yaml
Releasing the Mighty to the world.
> chore: upgrade fondue-tokens to next version - mighty tokens

- .github/pull_request_template.md
Let's try this. Should appear on Pull Request body after merge.
> chore: Add a Pull request template for Definition of done.

- src/components/SegmentedControls/SegmentedControls.tsx
Reported memory leak.  `useEffect` hook was missing dependencies.
> fix(SegmentedControls): add dependencies to hook and conditions for state logic

- src/components/LegacyTooltip/LegacyTooltip.cy.tsx
- src/components/LegacyTooltip/LegacyTooltip.stories.tsx
- src/components/LegacyTooltip/LegacyTooltip.tsx
- src/components/Toast/Toast.tsx
Needed for [Clickup Task](https://app.clickup.com/t/8692mvr65) and [PR](https://github.com/Frontify/web-app/pull/1662)
@todo:
[ x ] update tests
[ x ] add storybook story
> feat(LegacyTooltip): add withStrongBorder prop

- src/components/Dialog/Dialog.cy.tsx
- src/hooks/index.ts
- src/hooks/useMobileDetection.ts
- src/utilities/dialogs/Overlay.tsx
- [-] User interface and experience have been verified by a designer (To be discussed on Monday)
> fix(Dialog): Set default width on mobile view.

- src/components/Tooltip/Tooltip.stories.tsx
- src/components/Tooltip/Tooltip.tsx
> fix(Tooltip): Minor Styling issues

- src/components/Tabs/Tabs.cy.tsx
- src/components/Tabs/Tabs.stories.tsx
- src/components/Tabs/Tabs.tsx
Size is not the only enum so changing to union types will be done in another PR.
> fix(Tabs): Size to change both font-size and height of TabItem.

- src/components/Dialog/Dialog.cy.tsx
- src/components/Dialog/Dialog.stories.tsx
- src/utilities/dialogs/Overlay.tsx
Quick Fix for Dialog width issue on mobile view.
verticalAlignment and position will be discussed later.
> fix(Dialog): set a fixed width of 90vw on mobile view.

- src/components/Breadcrumbs/BreadcrumbItem.tsx
- src/components/Breadcrumbs/CurrentBreadcrumbItem.tsx
ClickUp: https://app.clickup.com/t/869362mux
> fix(Breadcrumbs): remove max width styling

- src/components/FormField/FormField.tsx
- src/components/NumberInput/NumberInput.tsx
Small update to reach `AA` accessibly
> fix(NumberInput, FormField): update aria labels

- src/components/Dialog/Dialog.stories.tsx
- src/components/Tooltip/InContextTooltip.stories.tsx
- src/components/Tooltip/Tooltip.stories.tsx
- src/components/Tooltip/Tooltip.tsx
- src/hooks/useToggleOverlay.ts
Tooltip improvements.
Needs Review from Lidija before merging.
> fix(Tooltip): focus and trigger

- src/components/Tabs/TabItem.tsx
- src/hooks/useFocusTrap.cy.tsx
- src/hooks/useFocusTrap.ts
- src/hooks/useToggleOverlay.ts
- src/utilities/dialogs/Overlay.tsx
- updated focus trap
- removed close modal onBlur 
- removed content of non active tab item
> fix: focus trap

- src/components/RichTextEditor/serializer/markdown/__tests__/MarkdownToSlate.spec.ts
- src/components/RichTextEditor/serializer/markdown/__tests__/SlateToMarkdown.spec.ts
- src/components/RichTextEditor/serializer/markdown/__tests__/fixtures/link.ts
- src/components/RichTextEditor/serializer/markdown/utils.ts
https://app.clickup.com/t/2523021/TASK-7974
> fix: Rich text editor xss vulnerability 

- src/components/TextInput/TextInput.cy.tsx
- src/components/TextInput/TextInput.stories.tsx
- src/components/TextInput/TextInput.tsx
https://app.clickup.com/t/8692y2u0c
> fix: updated focus ring on input field

- src/components/RichTextEditor/Plugins/CheckboxListPlugin/CheckboxListElement.tsx
- src/components/RichTextEditor/RichTextEditor.tsx
- src/components/RichTextEditor/__tests__/TextStylePlugin.cy.tsx
- src/components/RichTextEditor/helpers/exampleValues/exampleValues.ts
Changes made:
- Added aria label
- removed unneccessary wrapper
- removed invalid example data
> fix: [TASK-9412] Make Richtext Checklist Accessible

- src/components/Checkbox/Checkbox.tsx
- src/components/Checklist/Checklist.tsx
- src/components/FormField/FormField.tsx
- src/components/LegacyTooltip/LegacyTooltip.tsx
- src/components/SegmentedControls/SegmentedControls.tsx
- src/components/TextInput/TextInput.stories.tsx
- src/components/TextInput/TextInput.tsx
- src/utilities/input.tsx
Fixed Components:
- Number Input
- Text Input
- Text Area
- Multi Imput
- RTE -> Empty
- Checklist
- RadioList
- Segmented Controls
> fix: [a11y] Fix a1y issues in Fonude

- .changeset/chilly-bananas-mix.md
- packages/fondue/src/components/RichTextEditor/serializer/markdown/__tests__/MarkdownToSlate.spec.ts
- packages/fondue/src/components/RichTextEditor/serializer/markdown/__tests__/SlateToMarkdown.spec.ts
- packages/fondue/src/components/RichTextEditor/serializer/markdown/__tests__/fixtures/paragraph.ts
- packages/fondue/src/components/RichTextEditor/serializer/markdown/deserializer/deserialize.ts
- packages/fondue/src/components/RichTextEditor/serializer/markdown/serializer/serialize.ts
- packages/fondue/src/components/RichTextEditor/serializer/serializeToHtml.spec.ts
https://app.clickup.com/t/2523021/TASK-7703
> fix: disappearing line break made with shortcut Shift-Enter

- .changeset/sharp-humans-talk.md
- packages/fondue/src/components/RichTextEditor/Plugins/ListPlugin/ListItemContentMarkupElement.tsx
- packages/fondue/src/components/RichTextEditor/serializer/nodes/checkItem.ts
- packages/fondue/src/components/RichTextEditor/serializer/utils/serializeNodeToHtmlRecursive.spec.ts
- packages/fondue/src/components/RichTextEditor/serializer/utils/serializeNodeToHtmlRecursive.ts
https://app.clickup.com/t/2523021/TASK-10428
> fix(RTE): lic serialization is wrong

- .changeset/fast-ties-crash.md
- packages/fondue/fondueComponents.vite.config.ts
- packages/fondue/package.json
- packages/fondue/src/fondueComponents.ts
- packages/fondue/vite.config.ts
- pnpm-lock.yaml
Add Export of new Components to fondue
> feat: export new components from fondue

- packages/fondue/src/components/FilterableMultiSelect/FilterableMultiSelect.cy.tsx
- packages/fondue/src/components/FilterableMultiSelect/FilterableMultiSelect.stories.tsx
- packages/fondue/src/components/FilterableMultiSelect/FilterableMultiSelect.tsx
- packages/fondue/src/components/FilterableMultiSelect/helpers.ts
- packages/fondue/src/components/FilterableMultiSelect/index.ts
> feat: Introducing FilterableMultiSelect

- .changeset/rotten-turtles-march.md
add versionbump that was forgotten in https://github.com/Frontify/fondue/pull/1769
> add version

- .github/workflows/changeset-check.yaml
- packages/icons/src/index.ts
Automates check for `.changeset/` files in PR
After merging, we need to add to "Required" steps in branch protection
> ci: changeset workflow

- packages/components/.prettierignore
- packages/components/CHANGELOG.md
- packages/fondue/.prettierignore
- packages/fondue/.storybook/preview-head.html
- packages/fondue/CHANGELOG.md
- packages/fondue/cypress/support/component-index.html
- packages/fondue/src/components/DatePicker/DatePicker.css
- packages/fondue/src/styles.css
- packages/icons/.prettierignore
- fixes `prettier` error in the project
- adds `CHANGELOG.md` to ignore file
> chore: fix prettier errors and add changelog to prettierignore

- .changeset/fifty-students-pretend.md
- packages/fondue/src/components/Accordion/Accordion.stories.tsx
- packages/fondue/src/components/LinkChooser/LinkChooser.stories.tsx
- packages/fondue/src/components/LinkChooser/LinkChooser.tsx
deprecated the linkChooser, so we can soon remove it (and its deps)
> chore: deprecating linkChooser

- packages/components/scripts/templates/__tests__/component.ct.tsx
- packages/components/scripts/templates/__tests__/component.spec.tsx
- packages/components/scripts/templates/component.ts
- packages/components/scripts/templates/styles/componentStyles.tsx
- packages/components/scripts/transforms.ts
Fixes the casing of the constant to be "UPPERCASE_SNAKE_CASE"
> fix: component name casing in test file

- .changeset/weak-hounds-burn.md
- packages/components/tailwind.config.ts
- packages/fondue/tailwind.config.ts
This is a follow up PR regarding this task and this slack comment.
#86942nt20
https://frontify.slack.com/archives/C06D0LAQFB4/p1714397441925269?thread_ts=1714395981.927589&cid=C06D0LAQFB4
> refactor: updated blue ring color to reach contrast ratio compliance

- .changeset/nice-papayas-join.md
- packages/components/src/components/LoadingBar/LoadingBar.tsx
- packages/components/src/components/LoadingBar/styles/loadingBarStyles.ts
- packages/components/src/components/LoadingBar/tests/LoadingBar.ct.tsx
> fix: loading bar 0%

- .changeset/shaggy-lamps-camp.md
- packages/components/src/components/Checkbox/Checkbox.stories.tsx
- packages/components/src/components/Checkbox/styles/checkboxStyles.ts
- packages/components/src/components/Label/Label.stories.tsx
- packages/components/src/components/Label/Label.tsx
- packages/components/src/components/TextInput/TextInput.stories.tsx
- packages/components/src/components/TextInput/styles/textInputStyles.ts
Pair designed with Johanna
Task CU-8694j3acm CU-8694j3a71 CU-8694j3a37
> fix: design review

- .changeset/flat-jars-change.md
- packages/components/MIGRATING.md
- packages/components/src/components/Checkbox/Checkbox.stories.tsx
- packages/components/src/components/Checkbox/Checkbox.tsx
- packages/components/src/components/Divider/Divider.tsx
- packages/components/src/components/Flyout/Flyout.stories.tsx
- packages/components/src/components/Flyout/Flyout.tsx
- packages/components/src/components/Flyout/styles/flyoutStyles.ts
- packages/components/src/components/Label/Label.stories.tsx
- packages/components/src/components/Label/Label.tsx
- packages/components/src/components/LoadingBar/LoadingBar.tsx
- packages/components/src/components/SegmentedControl/SegmentedControl.stories.tsx
- packages/components/src/components/SegmentedControl/SegmentedControl.tsx
- packages/components/src/components/TextInput/TextInput.stories.tsx
- packages/components/src/components/TextInput/TextInput.tsx
- packages/fondue/src/components/Button/Button.stories.tsx
- packages/fondue/src/components/Checkbox/Checkbox.stories.tsx
- packages/fondue/src/components/Divider/Divider.stories.tsx
- packages/fondue/src/components/Divider/Divider.tsx
- packages/fondue/src/components/Flyout/Flyout.stories.tsx
- packages/fondue/src/components/InlineDialog/InContextInlineDialog.stories.tsx
- packages/fondue/src/components/InputLabel/InputLabel.stories.tsx
- packages/fondue/src/components/LegacyTooltip/LegacyTooltip.stories.tsx
- packages/fondue/src/components/LegacyTooltip/LegacyTooltip.tsx
- packages/fondue/src/components/LoadingBar/LoadingBar.stories.tsx
- packages/fondue/src/components/LoadingBar/LoadingBar.tsx
- packages/fondue/src/components/Popover/Popover.stories.tsx
- packages/fondue/src/components/SegmentedControls/SegmentedControls.stories.tsx
- packages/fondue/src/components/TextInput/TextInput.stories.tsx
- packages/fondue/src/components/Tooltip/Tooltip.stories.tsx
Added missing JSDoc
Added warnings in stories about deprecation
Added the migrating from LoadingBar
Aligned the footer of Flyout the same way we did with Dialog
> chore: fix few more things

- .changeset/brave-comics-own.md
- packages/fondue/src/components/RichTextEditor/Plugins/ColumnBreakPlugin/types.ts
- packages/fondue/src/components/RichTextEditor/RichTextEditor.tsx
- packages/fondue/src/components/RichTextEditor/__tests__/RichTextEditor.cy.tsx
- packages/fondue/src/components/RichTextEditor/serializer/serializeToHtml.spec.ts
- packages/fondue/src/components/RichTextEditor/serializer/serializeToHtml.ts
[This PR](https://github.com/Frontify/fondue/pull/1899) added the custom class prop to RTE, however it was not added to the serializer.
In addition, the GAP property is now applied even if custom class is provided.
> fix(RTE): serializer is missing custom class

- .changeset/loud-waves-fly.md
- packages/components/src/components/Tooltip/Tooltip.stories.tsx
- packages/components/src/components/Tooltip/Tooltip.tsx
- packages/components/src/components/Tooltip/__tests__/Tooltip.ct.tsx
- add external control props to tooltip
CU-8694v8rz3
> feat: add external control to tooltip

- .changeset/neat-cars-reply.md
- packages/components/src/components/Dialog/Dialog.stories.tsx
- packages/components/src/components/Dialog/Dialog.tsx
- packages/components/src/components/Dialog/styles/dialog.module.scss
- added prop `verticalAlign` to enable aligning the dialog to the top
> feat: add ability to align the dialog vertically

- .github/workflows/preview-storybook-pr.yaml
- .github/workflows/preview-storybook.yaml
- packages/charts/.storybook/main.ts
- packages/charts/.storybook/preview-head.html
- packages/components/.storybook/main.ts
- packages/components/.storybook/preview-head.html
- packages/fondue/.storybook/main.ts
- packages/fondue/.storybook/preview-head.html
- packages/icons/.storybook/main.ts
- packages/icons/.storybook/preview-head.html
- storybook-docs/.storybook/main.ts
Deploy of commits on `main` on: https://beta-fondue-components.frontify.com/
Deploy of PRs on: `https://beta-fondue-components.frontify.com/pr-preview/pr-[PR ID]/`
- the one for this PR as an example: https://beta-fondue-components.frontify.com/pr-preview/pr-1928/
> ci: deploy Storybook to GitHub Pages

- packages/components/src/components/Dialog/Dialog.stories.tsx
> docs: add story for external control

- .changeset/silent-dots-guess.md
- packages/fondue/src/components/RichTextEditor/Plugins/ListPlugin/ListItemContentMarkupElement.tsx
- packages/fondue/src/components/RichTextEditor/serializer/utils/serializeNodeToHtmlRecursive.spec.ts
- packages/fondue/src/components/RichTextEditor/serializer/utils/serializeNodeToHtmlRecursive.ts
https://app.clickup.com/t/2523021/TASK-9133
> fix(RTE): column break classes are applied twice to lic element

- .changeset/tricky-ravens-return.md
- packages/fondue/src/components/Checkbox/Checkbox.tsx
- packages/fondue/src/components/InputLabel/InputLabel.tsx
- packages/fondue/src/components/RadioList/RadioList.tsx
- packages/fondue/src/components/Slider/Slider.cy.tsx
- packages/fondue/src/components/Slider/Slider.tsx
- packages/fondue/src/components/Switch/Switch.tsx
- packages/fondue/src/components/Textarea/Textarea.tsx
Task id: [2523021/TASK-11748](https://app.clickup.com/t/2523021/TASK-11748)
Task id: [2523021/TASK-11749](https://app.clickup.com/t/2523021/TASK-11749)
> fix: multiple aria attribute adjustments

- .changeset/serious-jobs-build.md
- packages/components/.storybook/main.ts
- packages/components/src/components/Select/utils.ts
- fix filtering in combobox
- exclude storybook caches from vite dependency optimisation to fix startup
> fix: combobox filtering fix

- .changeset/lovely-bulldogs-brush.md
- packages/components/MIGRATING.md
- packages/components/src/components/Dropdown/Dropdown.tsx
> feat: add dropdown migration guide

- .changeset/rare-queens-count.md
- packages/components/src/components/Dropdown/Dropdown.stories.tsx
- packages/components/src/components/Dropdown/Dropdown.tsx
- packages/components/src/components/Dropdown/__tests__/Dropdown.ct.tsx
- packages/components/src/components/Dropdown/styles/dropdown.module.scss
- packages/components/src/components/Tooltip/Tooltip.tsx
- packages/components/src/utilities/domUtilities.ts
So we have the same API as the Tooltip
> fix: add missing side dropdown

- .changeset/sharp-fireants-know.md
- packages/components/src/components/Select/Combobox.tsx
- packages/components/src/components/Select/Select.stories.tsx
- packages/components/src/components/Select/Select.tsx
- packages/components/src/components/Select/__tests__/Combobox.ct.tsx
- packages/components/src/components/Select/__tests__/Select.ct.tsx
- packages/components/src/components/Select/styles/select.module.scss
- packages/components/src/components/TextInput/styles/text.module.scss
> feat: sync select with design system

- .changeset/silver-seals-share.md
- packages/components/src/index.ts
add missing color picker export
> feat: add missing color picker export

- .changeset/ten-clocks-lie.md
- packages/components/src/components/Select/Select.tsx
- packages/components/src/components/Select/__tests__/Select.ct.tsx
- packages/components/src/components/Select/styles/select.module.scss
- packages/components/src/components/TextInput/__tests__/TextInput.ct.tsx
- packages/components/src/components/TextInput/styles/text.module.scss
- packages/components/src/helpers/constants.ts
> fix: prevent focus styles duplication 

- .changeset/small-windows-live.md
- packages/components/src/components/Switch/styles/switch.module.scss
> fix: prevent box-sizing override from normalization scripts in web app

- .changeset/itchy-dryers-poke.md
- packages/components/src/components/Dialog/Dialog.stories.tsx
- packages/components/src/components/Dialog/Dialog.tsx
- packages/components/src/components/Dialog/styles/dialog.module.scss
- packages/components/src/components/Flyout/Flyout.tsx
- packages/components/src/components/Tooltip/Tooltip.tsx
- packages/components/src/components/Tooltip/styles/tooltip.module.scss
> fix: tooltip/flyout in dialog

- .changeset/orange-falcons-kneel.md
- packages/components/src/components/Flyout/Flyout.stories.tsx
- packages/components/src/components/Flyout/Flyout.tsx
- packages/components/src/components/Flyout/__tests__/Flyout.ct.tsx
> feat: add no padding option to flyout

- .changeset/brave-radios-unite.md
- packages/components/src/components/Dialog/styles/dialog.module.scss
> fix: dialog missing spacing when shrunk by viewport

- .changeset/rich-rice-explain.md
- packages/components/src/components/Dialog/Dialog.tsx
- packages/components/src/components/Dialog/styles/dialog.module.scss
- fix hidden dialog when modal=false
- add custom underlay for non-modal cases
> fix: non modal dialog hidden

- .changeset/good-olives-juggle.md
- packages/components/src/components/Dialog/Dialog.stories.tsx
- packages/components/src/components/Dialog/Dialog.tsx
- packages/components/src/components/Dialog/styles/dialog.module.scss
Allow header to expand full width
> fix: add full width wrapper in the header to allow more content

- .changeset/cyan-buckets-switch.md
- packages/components/src/components/Dialog/styles/dialog.module.scss
> fix: dialog overflowing bottom of viewport in mobile

- .changeset/gold-maps-juggle.md
- packages/components/src/components/Tooltip/Tooltip.stories.tsx
- packages/components/src/components/Tooltip/Tooltip.tsx
- packages/components/src/components/Tooltip/__tests__/Tooltip.ct.tsx
CU-8695t5fjm
more on this issue:
https://github.com/radix-ui/primitives/discussions/560
https://github.com/radix-ui/primitives/issues/2096
> fix: tooltip data-state conflicts with other components

- .changeset/swift-squids-shop.md
- packages/fondue/src/components/RichTextEditor/Plugins/LinkPlugin/FloatingLink/CustomFloatingLink.tsx
> feat(RTE): portal the link modal

- .changeset/selfish-planets-help.md
- packages/components/src/components/Tooltip/Tooltip.stories.tsx
- packages/components/src/components/Tooltip/Tooltip.tsx
- packages/components/src/components/Tooltip/__tests__/Tooltip.ct.tsx
> fix: revert "fix: tooltip data-state conflicts with other components"

- .changeset/large-mugs-refuse.md
- packages/components/src/components/Dialog/Dialog.tsx
- packages/components/src/components/Dropdown/Dropdown.tsx
- packages/components/src/components/Flyout/Flyout.tsx
- packages/components/src/components/Tooltip/Tooltip.stories.tsx
- packages/components/src/components/Tooltip/Tooltip.tsx
- packages/components/src/components/Tooltip/__tests__/Tooltip.ct.tsx
> feat: expose asChild prop on trigger components

- .changeset/quiet-pillows-listen.md
- packages/components/src/components/Dropdown/Dropdown.stories.tsx
- packages/components/src/components/Dropdown/styles/dropdown.module.scss
- adjusted css selector
CU-8695uhdt2
> fix: fix dropdown group dividers

- .changeset/metal-onions-flash.md
- packages/components/src/components/Dropdown/Dropdown.stories.tsx
- packages/components/src/components/Dropdown/Dropdown.tsx
- packages/components/src/components/Dropdown/styles/dropdown.module.scss
- packages/components/src/components/Select/Combobox.tsx
- packages/components/src/components/Select/Select.stories.tsx
- packages/components/src/components/Select/Select.tsx
- packages/components/src/components/Select/SelectItem.tsx
- packages/components/src/components/Select/SelectMenu.tsx
- packages/components/src/components/Select/styles/select.module.scss
- fix overflow of ext
- allow menu to be wider than the trigger
- added prop for aligning the menu
- added stories
- fixed scss ordering issues
CU-8695w8g35
> fix: adress overflow issues on select component

- .changeset/popular-points-clean.md
- packages/components/src/components/Dropdown/Dropdown.stories.tsx
- packages/components/src/components/Dropdown/Dropdown.tsx
- packages/components/src/components/Dropdown/styles/dropdown.module.scss
> feat(DropdownItem): add ability to control item height and padding:

- .changeset/thick-bugs-jam.md
- packages/components/src/components/Flyout/Flyout.tsx
- packages/components/src/components/Flyout/styles/flyout.module.scss
- packages/components/src/utilities/shadow.module.scss
> feat(Flyout): add rounded and shadow options

- .changeset/olive-pianos-hang.md
- packages/components/src/components/Flyout/Flyout.stories.tsx
- packages/components/src/components/Flyout/Flyout.tsx
- packages/components/src/components/Flyout/styles/flyout.module.scss
> feat(Flyout): add width prop

- .changeset/six-pugs-dream.md
- packages/components/package.json
- packages/components/src/components/ScrollArea/styles/scrollArea.module.scss
- pnpm-lock.yaml
CU-8696atvbm
fixed: https://github.com/radix-ui/primitives/pull/2945
> fix(ScrollArea): scroll content overflowing horizontally

- .changeset/warm-geese-rule.md
- packages/components/src/components/Tabs/Tabs.tsx
- packages/components/src/components/Tabs/styles/tabs.module.scss
> fix: cleanup tabs component

- .changeset/old-needles-stare.md
- packages/components/src/components/Dropdown/Dropdown.tsx
- packages/components/src/components/Dropdown/styles/dropdown.module.scss
> fix(Dropdown): missing styling for sub items and padding for submenu

- .changeset/kind-humans-exercise.md
- packages/components/src/components/Tabs/styles/tabs.module.scss
- adds missing box sizing rule
> fix: add box sizing for tabs

- .changeset/lovely-beers-exist.md
- packages/components/src/components/Dropdown/styles/dropdown.module.scss
- align styles with figma design
- text color
- background color for disabled items
CU-8696qey04
> fix: align styles with figma design

- .changeset/fast-toes-relate.md
- packages/components/src/components/ColorPicker/ColorPickerInput.tsx
- packages/components/src/components/ColorPicker/styles/colorInput.module.scss
- allow for focusing the clear button
- add proper focus styles
> fix: a11y improvements for color input element

- .changeset/light-geese-switch.md
- packages/components/src/components/Dialog/Dialog.stories.tsx
- packages/components/src/components/Dialog/Dialog.tsx
- packages/components/src/components/Dropdown/Dropdown.stories.tsx
- packages/components/src/components/Dropdown/Dropdown.tsx
- packages/components/src/components/Flyout/Flyout.stories.tsx
- packages/components/src/components/Flyout/Flyout.tsx
- packages/components/src/components/Tooltip/Tooltip.tsx
> fix(`Triggers`): nesting triggers causes one of them to not work

- .changeset/green-kiwis-reflect.md
- packages/components/src/components/Box/Box.tsx
- packages/components/src/components/Divider/Divider.tsx
- packages/components/src/components/Flex/Flex.tsx
- packages/components/src/components/Grid/Grid.tsx
- packages/components/src/components/Section/Section.tsx
> feat(Layout): add forward ref to layout components

- .changeset/chilly-readers-shake.md
- .changeset/silver-cows-scream.md
- packages/components/src/components/Dropdown/Dropdown.stories.tsx
- packages/components/src/components/Dropdown/Dropdown.tsx
- packages/components/src/components/Dropdown/__tests__/Dropdown.ct.tsx
- packages/components/src/components/Dropdown/hooks/useProcessedChildren.tsx
- packages/components/src/components/Dropdown/styles/dropdown.module.scss
- allow for link items in dropdown
- added option to prevent focusing the trigger on close
> feat: dropdown improvements

- .changeset/olive-sheep-relate.md
- packages/components/src/components/Flyout/styles/flyout.module.scss
> fix(Flyout): overlay does not cover page content (mobile)

- .changeset/lucky-bottles-judge.md
- packages/components/src/components/ColorPicker/ColorPickerInput.tsx
> fix: prevent ColorPicker.Input from submitting forms

- .changeset/short-wombats-crash.md
- packages/components/src/components/Dropdown/__tests__/Dropdown.ct.tsx
- packages/components/src/components/Dropdown/styles/dropdown.module.scss
> feat: align dropdown colors with design

- .changeset/shy-baboons-mix.md
- packages/components/src/components/Tabs/Tabs.stories.tsx
- packages/components/src/components/Tabs/Tabs.tsx
- packages/components/src/components/Tabs/__tests__/Tabs.ct.tsx
- packages/components/src/components/Tabs/styles/tabs.module.scss
> feat(Tabs): add padding control

- .changeset/large-points-hope.md
- packages/fondue/src/components/DatePicker/DatePicker.tsx
> fix: specify popper container

- .changeset/silver-glasses-sing.md
- packages/components/src/components/Dropdown/Dropdown.stories.tsx
- packages/components/src/components/Dropdown/Dropdown.tsx
- packages/components/src/components/Dropdown/styles/dropdown.module.scss
> feat(Dropdown): add radius, shadow, and width control

- packages/components/src/components/Dropdown/Dropdown.stories.tsx
- packages/components/src/components/Dropdown/Dropdown.tsx
- packages/components/src/components/Dropdown/styles/dropdown.module.scss
> Revert "feat(Dropdown): add radius, shadow, and width control"

- .changeset/short-weeks-suffer.md
- packages/fondue/src/components/DatePicker/DatePicker.stories.tsx
- packages/fondue/src/components/DatePicker/DatePicker.tsx
- packages/fondue/src/components/DatePicker/styles.css
- allows using the datepicker inline -> show picker without popper
CU-8697n21d1
> fix: add option to display inline

- .changeset/modern-camels-agree.md
- packages/components/src/components/Box/styles/box.module.scss
- packages/components/src/components/ColorPicker/styles/colorInput.module.scss
- packages/components/src/components/ColorPicker/styles/customColorPicker.module.scss
- packages/components/src/components/Dialog/styles/dialog.module.scss
- packages/components/src/components/Dropdown/styles/dropdown.module.scss
- packages/components/src/components/Flex/styles/flex.module.scss
- packages/components/src/components/Flyout/styles/flyout.module.scss
- packages/components/src/components/Grid/styles/grid.module.scss
- packages/components/src/components/ScrollArea/styles/scrollArea.module.scss
- packages/components/src/components/Section/styles/section.module.scss
- packages/components/src/components/SegmentedControl/styles/segmentedControl.module.scss
- packages/components/src/components/Select/styles/select.module.scss
- packages/components/src/components/Slider/styles/slider.module.scss
- packages/components/src/components/Switch/styles/switch.module.scss
- packages/components/src/components/Table/styles/table.module.scss
- packages/components/src/components/Tabs/styles/tabs.module.scss
- packages/components/src/components/TextInput/styles/text.module.scss
- packages/components/src/components/Tooltip/styles/tooltip.module.scss
- packages/components/src/helpers/layout.module.scss
- packages/components/src/styles.scss
- packages/components/src/utilities/focusStyle.module.scss
- packages/components/src/utilities/mediaQuery.module.scss
- packages/components/src/utilities/shadow.module.scss
- packages/components/src/utilities/sizeToken.module.scss
- packages/components/src/utilities/text.module.scss
- packages/components/src/utilities/transitions.module.scss
- packages/components/vite.config.ts
Update the notation to please the Sass compiler as the next major version will break these.
> chore: update Sass notation for breaking changes in next version

- .changeset/brown-paws-approve.md
- packages/components/src/components/Dropdown/Dropdown.tsx
> fix(Dropdown): add missing modal prop (and set to false by default)

- CONTRIBUTING.md
Found a few small things which might be good to know in the future.
> chore: update CONTRIBUTING

- .changeset/hip-pears-argue.md
- .changeset/quiet-beans-brake.md
- packages/components/MIGRATING.md
- packages/components/src/components/LoadingCircle/LoadingCircle.stories.tsx
- packages/components/src/components/LoadingCircle/LoadingCircle.tsx
- packages/components/src/components/LoadingCircle/styles/loadingCircleStyles.module.scss
- packages/components/src/components/LoadingCircle/tests/LoadingCircle.ct.tsx
- packages/components/src/components/Table/Table.stories.tsx
- packages/components/src/components/Table/Table.tsx
- packages/components/src/components/Table/__tests__/Table.ct.tsx
- packages/components/src/components/Table/styles/table.module.scss
- packages/fondue/src/components/LoadingCircle/LoadingCircle.stories.tsx
- packages/fondue/src/components/LoadingCircle/LoadingCircle.tsx
- Refactored `LoadingCircle` component
- Added loading state to Table Header Component
> feat: Add loading state to Table Header Cell

- .changeset/nine-flowers-compare.md
- packages/components/src/components/Dropdown/Dropdown.stories.tsx
- packages/components/src/components/Dropdown/Dropdown.tsx
- packages/components/src/components/Dropdown/__tests__/Dropdown.ct.tsx
- packages/components/src/components/Dropdown/styles/dropdown.module.scss
- packages/components/src/components/Select/__tests__/Combobox.ct.tsx
- packages/components/src/components/Select/__tests__/Select.ct.tsx
- packages/components/src/components/Select/styles/select.module.scss
- adjust dropdown styles to match figma
- adjust dropdown item usage with link
- adjust select styles to match dropdown and figma
> feat: adjust dropdown and select styles to match figma

- .changeset/many-jokes-enjoy.md
- packages/components/src/components/ColorPicker/styles/colorInput.module.scss
> feat: add border around ColorPickers color swatch

- .changeset/short-lemons-kick.md
- packages/components/src/components/Label/Label.stories.tsx
- packages/components/src/components/Label/Label.tsx
- packages/components/src/components/Select/Combobox.tsx
- packages/components/src/components/Select/Select.tsx
- packages/components/src/components/Select/SelectMenu.tsx
- packages/components/src/components/Select/styles/select.module.scss
> feat(Select): add id prop to Select

- .changeset/little-walls-live.md
- packages/charts/src/components/AreaStackChart/AreaStackChart.tsx
- packages/charts/src/components/BarChart/BarChart.tsx
- packages/charts/src/components/LineChart/LineChart.tsx
- packages/charts/src/components/common/hooks/useMargin.spec.tsx
- packages/charts/src/components/common/hooks/useMargin.ts
The font change broke some of the charts, going to the root we found that we should have a fallback to handle these cases gracefully
> refactor(charts): add fallback margin to charts

- .changeset/proud-teachers-swim.md
- .changeset/soft-points-pump.md
- packages/components/src/components/Accordion/Accordion.stories.tsx
- packages/components/src/components/Flyout/Flyout.stories.tsx
- packages/components/src/components/Flyout/Flyout.tsx
- packages/components/src/components/Flyout/__tests__/Flyout.ct.tsx
- packages/fondue/src/components/Accordion/Accordion.stories.tsx
- packages/fondue/src/components/Accordion/Accordion.tsx
- packages/fondue/src/components/Accordion/AccordionHeader.stories.tsx
- packages/fondue/src/components/Accordion/AccordionHeader.tsx
- packages/fondue/src/components/Accordion/AccordionHeaderIcon.stories.tsx
- packages/fondue/src/components/Accordion/AccordionHeaderIcon.tsx
- add triggerOffset prop to `Flyout`Component
- improve deprecation notices for `Accordion`Component
> feat: add customizable triggerOffset for `Flyout` + improve accordion deprecation

- .changeset/rich-spies-scream.md
- packages/fondue/src/components/Breadcrumbs/BreadcrumbItem.tsx
- packages/fondue/src/components/Breadcrumbs/Breadcrumbs.stories.tsx
- packages/fondue/src/components/Breadcrumbs/CurrentBreadcrumbItem.tsx
> fix(Breadcrumbs): remove focus indicator on noninteractive items

- .changeset/smooth-gifts-confess.md
- packages/components/src/components/ScrollArea/ScrollArea.stories.tsx
- packages/components/src/components/ScrollArea/ScrollArea.tsx
- packages/components/src/components/ScrollArea/__tests__/ScrollArea.ct.tsx
- packages/components/src/components/ScrollArea/styles/scrollArea.module.scss
> feat: add scrollbar gutter

- .changeset/red-plums-repeat.md
- packages/fondue/src/components/Modal/Modal.tsx
See https://github.com/Frontify/fondue/pull/2240#discussion_r1975472680
CU-86982zvzh
> refactor(Modal): remove default z-index from legacy modal

- .changeset/brave-jokes-reply.md
- packages/components/src/components/Flyout/Flyout.stories.tsx
- packages/components/src/components/Flyout/Flyout.tsx
- packages/components/src/components/Flyout/__tests__/Flyout.ct.tsx
- packages/components/src/components/Flyout/styles/flyout.module.scss
- add prop to allow scrolling in body
CU-86985rx47
> feat: add scrollable flyout body

- .changeset/warm-tools-pump.md
- packages/components/src/components/Select/Select.stories.tsx
- packages/components/src/components/Select/styles/select.module.scss
> fix(Select): adjacent groups are missing a divider line

- .changeset/gorgeous-crabs-tickle.md
- packages/components/src/components/ColorPicker/ColorPickerInput.tsx
- packages/components/src/components/ColorPicker/styles/colorInput.module.scss
> fix(ColorPickerInput): align style with select

- .changeset/real-eggs-dress.md
- packages/components/src/components/Table/styles/table.module.scss
> fix(Table): button focus is truncated in header with 'truncate'

- .changeset/green-humans-switch.md
- packages/components/src/components/Accordion/Accordion.stories.tsx
- packages/components/src/components/Accordion/Accordion.tsx
- packages/components/src/components/Accordion/__tests__/Accordion.ct.tsx
> fix(Accordion): onclick handler in incorrect place

- .changeset/solid-doodles-pick.md
- packages/fondue/src/components/FormControl/FormControl.cy.tsx
- packages/fondue/src/components/FormControl/FormControl.stories.tsx
- packages/fondue/src/components/FormControl/FormControl.tsx
> fix(FormControl): incorrect color tokens

- .changeset/chilly-pens-count.md
- packages/components/src/components/Switch/styles/switch.module.scss
Container width calculation on load caused a glitch in the position
- removed usage of container query
CU-8698hhujv
> fix: switch handle animates from outside

- packages/components/src/components/Tabs/Tabs.stories.tsx
> feat(Tabs): add badge story to default tab style

- .changeset/clever-symbols-bet.md
- packages/components/src/components/Tabs/styles/tabs.module.scss
> chore(Tabs): add trigger click indicator

- .changeset/empty-cooks-design.md
- packages/components/src/components/Tabs/styles/tabs.module.scss
> chore(Tabs): change active tab indicators color

- .changeset/soft-gifts-heal.md
- packages/fondue/src/components/Divider/Divider.tsx
> feat(Divider): add as prop to define the element type to be used

- .changeset/twenty-ears-matter.md
- packages/components/src/components/Select/Select.stories.tsx
- packages/components/src/components/Select/SelectItem.tsx
- packages/components/src/components/Select/styles/select.module.scss
> feat(Select): add heading to select groups

- .changeset/happy-deer-occur.md
- packages/components/src/components/Switch/styles/switch.module.scss
> chore(Switch): add flex-shrink 0

- packages/components/src/components/Tokens/components/Tokens/TokenCollectionOverview.tsx
- packages/components/src/components/Tokens/previews/SemanticToken.tsx
- packages/fondue/legacyTokens/legacyTokens.tailwind.config.d.ts
- packages/tokens/src/buildTokens.ts
- fix tailwind types
- sort token previews
- fix shadow preview
> feat: token preview improvements

- .changeset/seven-doodles-stay.md
- packages/components/src/components/Divider/Divider.tsx
- packages/components/src/components/Divider/styles/borderStyles.module.scss
> chore(Divider): update dashed line style

- .changeset/puny-lamps-admire.md
- packages/charts/src/components/AreaStackChart/AreaStackChart.tsx
- packages/charts/src/components/BarChart/BarChart.tsx
- packages/charts/src/components/LineChart/LineChart.stories.tsx
- packages/charts/src/components/LineChart/LineChart.tsx
> fix: charts crosshair overlapping other content [CU-869a89rkf]

- .changeset/warm-ravens-begin.md
- packages/components/src/components/Dropdown/styles/dropdown.module.scss
- packages/components/src/components/Select/styles/select.module.scss
This should make them feel less sluggish.
> feat(Dropdown): remove hover transition in Select and Dropdown
